// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package dubbing

import (
	"context"
	"fmt"
)

type Voice struct {
	Id             int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Name           string `thrift:"name,2" frugal:"2,default,string" json:"name"`
	Tag            string `thrift:"tag,3" frugal:"3,default,string" json:"tag"`
	Avatar         string `thrift:"avatar,4" frugal:"4,default,string" json:"avatar"`
	SampleAudioUrl string `thrift:"sampleAudioUrl,5" frugal:"5,default,string" json:"sampleAudioUrl"`
}

func NewVoice() *Voice {
	return &Voice{}
}

func (p *Voice) InitDefault() {
}

func (p *Voice) GetId() (v int64) {
	return p.Id
}

func (p *Voice) GetName() (v string) {
	return p.Name
}

func (p *Voice) GetTag() (v string) {
	return p.Tag
}

func (p *Voice) GetAvatar() (v string) {
	return p.Avatar
}

func (p *Voice) GetSampleAudioUrl() (v string) {
	return p.SampleAudioUrl
}
func (p *Voice) SetId(val int64) {
	p.Id = val
}
func (p *Voice) SetName(val string) {
	p.Name = val
}
func (p *Voice) SetTag(val string) {
	p.Tag = val
}
func (p *Voice) SetAvatar(val string) {
	p.Avatar = val
}
func (p *Voice) SetSampleAudioUrl(val string) {
	p.SampleAudioUrl = val
}

func (p *Voice) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Voice(%+v)", *p)
}

var fieldIDToName_Voice = map[int16]string{
	1: "id",
	2: "name",
	3: "tag",
	4: "avatar",
	5: "sampleAudioUrl",
}

type Model struct {
	Id        string `thrift:"id,1" frugal:"1,default,string" json:"id"`
	Provider  string `thrift:"provider,2" frugal:"2,default,string" json:"provider"`
	Label     string `thrift:"label,3" frugal:"3,default,string" json:"label"`
	IsDefault bool   `thrift:"isDefault,4" frugal:"4,default,bool" json:"isDefault"`
}

func NewModel() *Model {
	return &Model{}
}

func (p *Model) InitDefault() {
}

func (p *Model) GetId() (v string) {
	return p.Id
}

func (p *Model) GetProvider() (v string) {
	return p.Provider
}

func (p *Model) GetLabel() (v string) {
	return p.Label
}

func (p *Model) GetIsDefault() (v bool) {
	return p.IsDefault
}
func (p *Model) SetId(val string) {
	p.Id = val
}
func (p *Model) SetProvider(val string) {
	p.Provider = val
}
func (p *Model) SetLabel(val string) {
	p.Label = val
}
func (p *Model) SetIsDefault(val bool) {
	p.IsDefault = val
}

func (p *Model) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Model(%+v)", *p)
}

var fieldIDToName_Model = map[int16]string{
	1: "id",
	2: "provider",
	3: "label",
	4: "isDefault",
}

type OptionsResp struct {
	Voices       []*Voice `thrift:"voices,1" frugal:"1,default,list<Voice>" json:"voices"`
	Emotions     []string `thrift:"emotions,2" frugal:"2,default,list<string>" json:"emotions"`
	Models       []*Model `thrift:"models,3" frugal:"3,default,list<Model>" json:"models"`
	CurrentModel *Model   `thrift:"currentModel,4,optional" frugal:"4,optional,Model" json:"currentModel,omitempty"`
}

func NewOptionsResp() *OptionsResp {
	return &OptionsResp{}
}

func (p *OptionsResp) InitDefault() {
}

func (p *OptionsResp) GetVoices() (v []*Voice) {
	return p.Voices
}

func (p *OptionsResp) GetEmotions() (v []string) {
	return p.Emotions
}

func (p *OptionsResp) GetModels() (v []*Model) {
	return p.Models
}

var OptionsResp_CurrentModel_DEFAULT *Model

func (p *OptionsResp) GetCurrentModel() (v *Model) {
	if !p.IsSetCurrentModel() {
		return OptionsResp_CurrentModel_DEFAULT
	}
	return p.CurrentModel
}
func (p *OptionsResp) SetVoices(val []*Voice) {
	p.Voices = val
}
func (p *OptionsResp) SetEmotions(val []string) {
	p.Emotions = val
}
func (p *OptionsResp) SetModels(val []*Model) {
	p.Models = val
}
func (p *OptionsResp) SetCurrentModel(val *Model) {
	p.CurrentModel = val
}

func (p *OptionsResp) IsSetCurrentModel() bool {
	return p.CurrentModel != nil
}

func (p *OptionsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OptionsResp(%+v)", *p)
}

var fieldIDToName_OptionsResp = map[int16]string{
	1: "voices",
	2: "emotions",
	3: "models",
	4: "currentModel",
}

type Job struct {
	Id        int64   `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Title     string  `thrift:"title,2" frugal:"2,default,string" json:"title"`
	Text      string  `thrift:"text,3" frugal:"3,default,string" json:"text"`
	VoiceId   *int64  `thrift:"voiceId,4,optional" frugal:"4,optional,i64" json:"voiceId,omitempty"`
	VoiceName *string `thrift:"voiceName,5,optional" frugal:"5,optional,string" json:"voiceName,omitempty"`
	Status    string  `thrift:"status,6" frugal:"6,default,string" json:"status"`
	AudioUrl  *string `thrift:"audioUrl,7,optional" frugal:"7,optional,string" json:"audioUrl,omitempty"`
	CreatedAt string  `thrift:"createdAt,8" frugal:"8,default,string" json:"createdAt"`
	UpdatedAt string  `thrift:"updatedAt,9" frugal:"9,default,string" json:"updatedAt"`
}

func NewJob() *Job {
	return &Job{}
}

func (p *Job) InitDefault() {
}

func (p *Job) GetId() (v int64) {
	return p.Id
}

func (p *Job) GetTitle() (v string) {
	return p.Title
}

func (p *Job) GetText() (v string) {
	return p.Text
}

var Job_VoiceId_DEFAULT int64

func (p *Job) GetVoiceId() (v int64) {
	if !p.IsSetVoiceId() {
		return Job_VoiceId_DEFAULT
	}
	return *p.VoiceId
}

var Job_VoiceName_DEFAULT string

func (p *Job) GetVoiceName() (v string) {
	if !p.IsSetVoiceName() {
		return Job_VoiceName_DEFAULT
	}
	return *p.VoiceName
}

func (p *Job) GetStatus() (v string) {
	return p.Status
}

var Job_AudioUrl_DEFAULT string

func (p *Job) GetAudioUrl() (v string) {
	if !p.IsSetAudioUrl() {
		return Job_AudioUrl_DEFAULT
	}
	return *p.AudioUrl
}

func (p *Job) GetCreatedAt() (v string) {
	return p.CreatedAt
}

func (p *Job) GetUpdatedAt() (v string) {
	return p.UpdatedAt
}
func (p *Job) SetId(val int64) {
	p.Id = val
}
func (p *Job) SetTitle(val string) {
	p.Title = val
}
func (p *Job) SetText(val string) {
	p.Text = val
}
func (p *Job) SetVoiceId(val *int64) {
	p.VoiceId = val
}
func (p *Job) SetVoiceName(val *string) {
	p.VoiceName = val
}
func (p *Job) SetStatus(val string) {
	p.Status = val
}
func (p *Job) SetAudioUrl(val *string) {
	p.AudioUrl = val
}
func (p *Job) SetCreatedAt(val string) {
	p.CreatedAt = val
}
func (p *Job) SetUpdatedAt(val string) {
	p.UpdatedAt = val
}

func (p *Job) IsSetVoiceId() bool {
	return p.VoiceId != nil
}

func (p *Job) IsSetVoiceName() bool {
	return p.VoiceName != nil
}

func (p *Job) IsSetAudioUrl() bool {
	return p.AudioUrl != nil
}

func (p *Job) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Job(%+v)", *p)
}

var fieldIDToName_Job = map[int16]string{
	1: "id",
	2: "title",
	3: "text",
	4: "voiceId",
	5: "voiceName",
	6: "status",
	7: "audioUrl",
	8: "createdAt",
	9: "updatedAt",
}

type TaskCreatedResp struct {
	TaskId string `thrift:"taskId,1" frugal:"1,default,string" json:"taskId"`
	Status string `thrift:"status,2" frugal:"2,default,string" json:"status"`
}

func NewTaskCreatedResp() *TaskCreatedResp {
	return &TaskCreatedResp{}
}

func (p *TaskCreatedResp) InitDefault() {
}

func (p *TaskCreatedResp) GetTaskId() (v string) {
	return p.TaskId
}

func (p *TaskCreatedResp) GetStatus() (v string) {
	return p.Status
}
func (p *TaskCreatedResp) SetTaskId(val string) {
	p.TaskId = val
}
func (p *TaskCreatedResp) SetStatus(val string) {
	p.Status = val
}

func (p *TaskCreatedResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TaskCreatedResp(%+v)", *p)
}

var fieldIDToName_TaskCreatedResp = map[int16]string{
	1: "taskId",
	2: "status",
}

type RecordsResp struct {
	Items    []*Job `thrift:"items,1" frugal:"1,default,list<Job>" json:"items"`
	Total    int64  `thrift:"total,2" frugal:"2,default,i64" json:"total"`
	Page     int32  `thrift:"page,3" frugal:"3,default,i32" json:"page"`
	PageSize int32  `thrift:"pageSize,4" frugal:"4,default,i32" json:"pageSize"`
}

func NewRecordsResp() *RecordsResp {
	return &RecordsResp{}
}

func (p *RecordsResp) InitDefault() {
}

func (p *RecordsResp) GetItems() (v []*Job) {
	return p.Items
}

func (p *RecordsResp) GetTotal() (v int64) {
	return p.Total
}

func (p *RecordsResp) GetPage() (v int32) {
	return p.Page
}

func (p *RecordsResp) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *RecordsResp) SetItems(val []*Job) {
	p.Items = val
}
func (p *RecordsResp) SetTotal(val int64) {
	p.Total = val
}
func (p *RecordsResp) SetPage(val int32) {
	p.Page = val
}
func (p *RecordsResp) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *RecordsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecordsResp(%+v)", *p)
}

var fieldIDToName_RecordsResp = map[int16]string{
	1: "items",
	2: "total",
	3: "page",
	4: "pageSize",
}

type GetOptionsReq struct {
	UserID int64 `thrift:"userID,1" frugal:"1,default,i64" json:"userID"`
}

func NewGetOptionsReq() *GetOptionsReq {
	return &GetOptionsReq{}
}

func (p *GetOptionsReq) InitDefault() {
}

func (p *GetOptionsReq) GetUserID() (v int64) {
	return p.UserID
}
func (p *GetOptionsReq) SetUserID(val int64) {
	p.UserID = val
}

func (p *GetOptionsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOptionsReq(%+v)", *p)
}

var fieldIDToName_GetOptionsReq = map[int16]string{
	1: "userID",
}

type GenerateDraftReq struct {
	UserID int64  `thrift:"userID,1" frugal:"1,default,i64" json:"userID"`
	Prompt string `thrift:"prompt,2" frugal:"2,default,string" json:"prompt"`
	Model  string `thrift:"model,3" frugal:"3,default,string" json:"model"`
}

func NewGenerateDraftReq() *GenerateDraftReq {
	return &GenerateDraftReq{}
}

func (p *GenerateDraftReq) InitDefault() {
}

func (p *GenerateDraftReq) GetUserID() (v int64) {
	return p.UserID
}

func (p *GenerateDraftReq) GetPrompt() (v string) {
	return p.Prompt
}

func (p *GenerateDraftReq) GetModel() (v string) {
	return p.Model
}
func (p *GenerateDraftReq) SetUserID(val int64) {
	p.UserID = val
}
func (p *GenerateDraftReq) SetPrompt(val string) {
	p.Prompt = val
}
func (p *GenerateDraftReq) SetModel(val string) {
	p.Model = val
}

func (p *GenerateDraftReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GenerateDraftReq(%+v)", *p)
}

var fieldIDToName_GenerateDraftReq = map[int16]string{
	1: "userID",
	2: "prompt",
	3: "model",
}

type PreviewReq struct {
	UserID   int64  `thrift:"userID,1" frugal:"1,default,i64" json:"userID"`
	Text     string `thrift:"text,2" frugal:"2,default,string" json:"text"`
	VoiceID  int64  `thrift:"voiceID,3" frugal:"3,default,i64" json:"voiceID"`
	Title    string `thrift:"title,4" frugal:"4,default,string" json:"title"`
	Settings []byte `thrift:"settings,5" frugal:"5,default,binary" json:"settings"`
}

func NewPreviewReq() *PreviewReq {
	return &PreviewReq{}
}

func (p *PreviewReq) InitDefault() {
}

func (p *PreviewReq) GetUserID() (v int64) {
	return p.UserID
}

func (p *PreviewReq) GetText() (v string) {
	return p.Text
}

func (p *PreviewReq) GetVoiceID() (v int64) {
	return p.VoiceID
}

func (p *PreviewReq) GetTitle() (v string) {
	return p.Title
}

func (p *PreviewReq) GetSettings() (v []byte) {
	return p.Settings
}
func (p *PreviewReq) SetUserID(val int64) {
	p.UserID = val
}
func (p *PreviewReq) SetText(val string) {
	p.Text = val
}
func (p *PreviewReq) SetVoiceID(val int64) {
	p.VoiceID = val
}
func (p *PreviewReq) SetTitle(val string) {
	p.Title = val
}
func (p *PreviewReq) SetSettings(val []byte) {
	p.Settings = val
}

func (p *PreviewReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PreviewReq(%+v)", *p)
}

var fieldIDToName_PreviewReq = map[int16]string{
	1: "userID",
	2: "text",
	3: "voiceID",
	4: "title",
	5: "settings",
}

type ExportReq struct {
	UserID   int64  `thrift:"userID,1" frugal:"1,default,i64" json:"userID"`
	Text     string `thrift:"text,2" frugal:"2,default,string" json:"text"`
	VoiceID  int64  `thrift:"voiceID,3" frugal:"3,default,i64" json:"voiceID"`
	Title    string `thrift:"title,4" frugal:"4,default,string" json:"title"`
	Settings []byte `thrift:"settings,5" frugal:"5,default,binary" json:"settings"`
}

func NewExportReq() *ExportReq {
	return &ExportReq{}
}

func (p *ExportReq) InitDefault() {
}

func (p *ExportReq) GetUserID() (v int64) {
	return p.UserID
}

func (p *ExportReq) GetText() (v string) {
	return p.Text
}

func (p *ExportReq) GetVoiceID() (v int64) {
	return p.VoiceID
}

func (p *ExportReq) GetTitle() (v string) {
	return p.Title
}

func (p *ExportReq) GetSettings() (v []byte) {
	return p.Settings
}
func (p *ExportReq) SetUserID(val int64) {
	p.UserID = val
}
func (p *ExportReq) SetText(val string) {
	p.Text = val
}
func (p *ExportReq) SetVoiceID(val int64) {
	p.VoiceID = val
}
func (p *ExportReq) SetTitle(val string) {
	p.Title = val
}
func (p *ExportReq) SetSettings(val []byte) {
	p.Settings = val
}

func (p *ExportReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ExportReq(%+v)", *p)
}

var fieldIDToName_ExportReq = map[int16]string{
	1: "userID",
	2: "text",
	3: "voiceID",
	4: "title",
	5: "settings",
}

type GetRecordsReq struct {
	UserID   int64  `thrift:"userID,1" frugal:"1,default,i64" json:"userID"`
	Search   string `thrift:"search,2" frugal:"2,default,string" json:"search"`
	Page     int32  `thrift:"page,3" frugal:"3,default,i32" json:"page"`
	PageSize int32  `thrift:"pageSize,4" frugal:"4,default,i32" json:"pageSize"`
}

func NewGetRecordsReq() *GetRecordsReq {
	return &GetRecordsReq{}
}

func (p *GetRecordsReq) InitDefault() {
}

func (p *GetRecordsReq) GetUserID() (v int64) {
	return p.UserID
}

func (p *GetRecordsReq) GetSearch() (v string) {
	return p.Search
}

func (p *GetRecordsReq) GetPage() (v int32) {
	return p.Page
}

func (p *GetRecordsReq) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *GetRecordsReq) SetUserID(val int64) {
	p.UserID = val
}
func (p *GetRecordsReq) SetSearch(val string) {
	p.Search = val
}
func (p *GetRecordsReq) SetPage(val int32) {
	p.Page = val
}
func (p *GetRecordsReq) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *GetRecordsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetRecordsReq(%+v)", *p)
}

var fieldIDToName_GetRecordsReq = map[int16]string{
	1: "userID",
	2: "search",
	3: "page",
	4: "pageSize",
}

type DeleteRecordReq struct {
	UserID int64 `thrift:"userID,1" frugal:"1,default,i64" json:"userID"`
	JobID  int64 `thrift:"jobID,2" frugal:"2,default,i64" json:"jobID"`
}

func NewDeleteRecordReq() *DeleteRecordReq {
	return &DeleteRecordReq{}
}

func (p *DeleteRecordReq) InitDefault() {
}

func (p *DeleteRecordReq) GetUserID() (v int64) {
	return p.UserID
}

func (p *DeleteRecordReq) GetJobID() (v int64) {
	return p.JobID
}
func (p *DeleteRecordReq) SetUserID(val int64) {
	p.UserID = val
}
func (p *DeleteRecordReq) SetJobID(val int64) {
	p.JobID = val
}

func (p *DeleteRecordReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteRecordReq(%+v)", *p)
}

var fieldIDToName_DeleteRecordReq = map[int16]string{
	1: "userID",
	2: "jobID",
}

type DubbingService interface {
	GetOptions(ctx context.Context, req *GetOptionsReq) (r *OptionsResp, err error)

	GenerateDraft(ctx context.Context, req *GenerateDraftReq) (r *TaskCreatedResp, err error)

	CreatePreview(ctx context.Context, req *PreviewReq) (r *TaskCreatedResp, err error)

	CreateExport(ctx context.Context, req *ExportReq) (r *TaskCreatedResp, err error)

	GetRecords(ctx context.Context, req *GetRecordsReq) (r *RecordsResp, err error)

	DeleteRecord(ctx context.Context, req *DeleteRecordReq) (r bool, err error)
}

type DubbingServiceGetOptionsArgs struct {
	Req *GetOptionsReq `thrift:"req,1" frugal:"1,default,GetOptionsReq" json:"req"`
}

func NewDubbingServiceGetOptionsArgs() *DubbingServiceGetOptionsArgs {
	return &DubbingServiceGetOptionsArgs{}
}

func (p *DubbingServiceGetOptionsArgs) InitDefault() {
}

var DubbingServiceGetOptionsArgs_Req_DEFAULT *GetOptionsReq

func (p *DubbingServiceGetOptionsArgs) GetReq() (v *GetOptionsReq) {
	if !p.IsSetReq() {
		return DubbingServiceGetOptionsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DubbingServiceGetOptionsArgs) SetReq(val *GetOptionsReq) {
	p.Req = val
}

func (p *DubbingServiceGetOptionsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DubbingServiceGetOptionsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DubbingServiceGetOptionsArgs(%+v)", *p)
}

var fieldIDToName_DubbingServiceGetOptionsArgs = map[int16]string{
	1: "req",
}

type DubbingServiceGetOptionsResult struct {
	Success *OptionsResp `thrift:"success,0,optional" frugal:"0,optional,OptionsResp" json:"success,omitempty"`
}

func NewDubbingServiceGetOptionsResult() *DubbingServiceGetOptionsResult {
	return &DubbingServiceGetOptionsResult{}
}

func (p *DubbingServiceGetOptionsResult) InitDefault() {
}

var DubbingServiceGetOptionsResult_Success_DEFAULT *OptionsResp

func (p *DubbingServiceGetOptionsResult) GetSuccess() (v *OptionsResp) {
	if !p.IsSetSuccess() {
		return DubbingServiceGetOptionsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DubbingServiceGetOptionsResult) SetSuccess(x interface{}) {
	p.Success = x.(*OptionsResp)
}

func (p *DubbingServiceGetOptionsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DubbingServiceGetOptionsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DubbingServiceGetOptionsResult(%+v)", *p)
}

var fieldIDToName_DubbingServiceGetOptionsResult = map[int16]string{
	0: "success",
}

type DubbingServiceGenerateDraftArgs struct {
	Req *GenerateDraftReq `thrift:"req,1" frugal:"1,default,GenerateDraftReq" json:"req"`
}

func NewDubbingServiceGenerateDraftArgs() *DubbingServiceGenerateDraftArgs {
	return &DubbingServiceGenerateDraftArgs{}
}

func (p *DubbingServiceGenerateDraftArgs) InitDefault() {
}

var DubbingServiceGenerateDraftArgs_Req_DEFAULT *GenerateDraftReq

func (p *DubbingServiceGenerateDraftArgs) GetReq() (v *GenerateDraftReq) {
	if !p.IsSetReq() {
		return DubbingServiceGenerateDraftArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DubbingServiceGenerateDraftArgs) SetReq(val *GenerateDraftReq) {
	p.Req = val
}

func (p *DubbingServiceGenerateDraftArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DubbingServiceGenerateDraftArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DubbingServiceGenerateDraftArgs(%+v)", *p)
}

var fieldIDToName_DubbingServiceGenerateDraftArgs = map[int16]string{
	1: "req",
}

type DubbingServiceGenerateDraftResult struct {
	Success *TaskCreatedResp `thrift:"success,0,optional" frugal:"0,optional,TaskCreatedResp" json:"success,omitempty"`
}

func NewDubbingServiceGenerateDraftResult() *DubbingServiceGenerateDraftResult {
	return &DubbingServiceGenerateDraftResult{}
}

func (p *DubbingServiceGenerateDraftResult) InitDefault() {
}

var DubbingServiceGenerateDraftResult_Success_DEFAULT *TaskCreatedResp

func (p *DubbingServiceGenerateDraftResult) GetSuccess() (v *TaskCreatedResp) {
	if !p.IsSetSuccess() {
		return DubbingServiceGenerateDraftResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DubbingServiceGenerateDraftResult) SetSuccess(x interface{}) {
	p.Success = x.(*TaskCreatedResp)
}

func (p *DubbingServiceGenerateDraftResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DubbingServiceGenerateDraftResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DubbingServiceGenerateDraftResult(%+v)", *p)
}

var fieldIDToName_DubbingServiceGenerateDraftResult = map[int16]string{
	0: "success",
}

type DubbingServiceCreatePreviewArgs struct {
	Req *PreviewReq `thrift:"req,1" frugal:"1,default,PreviewReq" json:"req"`
}

func NewDubbingServiceCreatePreviewArgs() *DubbingServiceCreatePreviewArgs {
	return &DubbingServiceCreatePreviewArgs{}
}

func (p *DubbingServiceCreatePreviewArgs) InitDefault() {
}

var DubbingServiceCreatePreviewArgs_Req_DEFAULT *PreviewReq

func (p *DubbingServiceCreatePreviewArgs) GetReq() (v *PreviewReq) {
	if !p.IsSetReq() {
		return DubbingServiceCreatePreviewArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DubbingServiceCreatePreviewArgs) SetReq(val *PreviewReq) {
	p.Req = val
}

func (p *DubbingServiceCreatePreviewArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DubbingServiceCreatePreviewArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DubbingServiceCreatePreviewArgs(%+v)", *p)
}

var fieldIDToName_DubbingServiceCreatePreviewArgs = map[int16]string{
	1: "req",
}

type DubbingServiceCreatePreviewResult struct {
	Success *TaskCreatedResp `thrift:"success,0,optional" frugal:"0,optional,TaskCreatedResp" json:"success,omitempty"`
}

func NewDubbingServiceCreatePreviewResult() *DubbingServiceCreatePreviewResult {
	return &DubbingServiceCreatePreviewResult{}
}

func (p *DubbingServiceCreatePreviewResult) InitDefault() {
}

var DubbingServiceCreatePreviewResult_Success_DEFAULT *TaskCreatedResp

func (p *DubbingServiceCreatePreviewResult) GetSuccess() (v *TaskCreatedResp) {
	if !p.IsSetSuccess() {
		return DubbingServiceCreatePreviewResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DubbingServiceCreatePreviewResult) SetSuccess(x interface{}) {
	p.Success = x.(*TaskCreatedResp)
}

func (p *DubbingServiceCreatePreviewResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DubbingServiceCreatePreviewResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DubbingServiceCreatePreviewResult(%+v)", *p)
}

var fieldIDToName_DubbingServiceCreatePreviewResult = map[int16]string{
	0: "success",
}

type DubbingServiceCreateExportArgs struct {
	Req *ExportReq `thrift:"req,1" frugal:"1,default,ExportReq" json:"req"`
}

func NewDubbingServiceCreateExportArgs() *DubbingServiceCreateExportArgs {
	return &DubbingServiceCreateExportArgs{}
}

func (p *DubbingServiceCreateExportArgs) InitDefault() {
}

var DubbingServiceCreateExportArgs_Req_DEFAULT *ExportReq

func (p *DubbingServiceCreateExportArgs) GetReq() (v *ExportReq) {
	if !p.IsSetReq() {
		return DubbingServiceCreateExportArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DubbingServiceCreateExportArgs) SetReq(val *ExportReq) {
	p.Req = val
}

func (p *DubbingServiceCreateExportArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DubbingServiceCreateExportArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DubbingServiceCreateExportArgs(%+v)", *p)
}

var fieldIDToName_DubbingServiceCreateExportArgs = map[int16]string{
	1: "req",
}

type DubbingServiceCreateExportResult struct {
	Success *TaskCreatedResp `thrift:"success,0,optional" frugal:"0,optional,TaskCreatedResp" json:"success,omitempty"`
}

func NewDubbingServiceCreateExportResult() *DubbingServiceCreateExportResult {
	return &DubbingServiceCreateExportResult{}
}

func (p *DubbingServiceCreateExportResult) InitDefault() {
}

var DubbingServiceCreateExportResult_Success_DEFAULT *TaskCreatedResp

func (p *DubbingServiceCreateExportResult) GetSuccess() (v *TaskCreatedResp) {
	if !p.IsSetSuccess() {
		return DubbingServiceCreateExportResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DubbingServiceCreateExportResult) SetSuccess(x interface{}) {
	p.Success = x.(*TaskCreatedResp)
}

func (p *DubbingServiceCreateExportResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DubbingServiceCreateExportResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DubbingServiceCreateExportResult(%+v)", *p)
}

var fieldIDToName_DubbingServiceCreateExportResult = map[int16]string{
	0: "success",
}

type DubbingServiceGetRecordsArgs struct {
	Req *GetRecordsReq `thrift:"req,1" frugal:"1,default,GetRecordsReq" json:"req"`
}

func NewDubbingServiceGetRecordsArgs() *DubbingServiceGetRecordsArgs {
	return &DubbingServiceGetRecordsArgs{}
}

func (p *DubbingServiceGetRecordsArgs) InitDefault() {
}

var DubbingServiceGetRecordsArgs_Req_DEFAULT *GetRecordsReq

func (p *DubbingServiceGetRecordsArgs) GetReq() (v *GetRecordsReq) {
	if !p.IsSetReq() {
		return DubbingServiceGetRecordsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DubbingServiceGetRecordsArgs) SetReq(val *GetRecordsReq) {
	p.Req = val
}

func (p *DubbingServiceGetRecordsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DubbingServiceGetRecordsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DubbingServiceGetRecordsArgs(%+v)", *p)
}

var fieldIDToName_DubbingServiceGetRecordsArgs = map[int16]string{
	1: "req",
}

type DubbingServiceGetRecordsResult struct {
	Success *RecordsResp `thrift:"success,0,optional" frugal:"0,optional,RecordsResp" json:"success,omitempty"`
}

func NewDubbingServiceGetRecordsResult() *DubbingServiceGetRecordsResult {
	return &DubbingServiceGetRecordsResult{}
}

func (p *DubbingServiceGetRecordsResult) InitDefault() {
}

var DubbingServiceGetRecordsResult_Success_DEFAULT *RecordsResp

func (p *DubbingServiceGetRecordsResult) GetSuccess() (v *RecordsResp) {
	if !p.IsSetSuccess() {
		return DubbingServiceGetRecordsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DubbingServiceGetRecordsResult) SetSuccess(x interface{}) {
	p.Success = x.(*RecordsResp)
}

func (p *DubbingServiceGetRecordsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DubbingServiceGetRecordsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DubbingServiceGetRecordsResult(%+v)", *p)
}

var fieldIDToName_DubbingServiceGetRecordsResult = map[int16]string{
	0: "success",
}

type DubbingServiceDeleteRecordArgs struct {
	Req *DeleteRecordReq `thrift:"req,1" frugal:"1,default,DeleteRecordReq" json:"req"`
}

func NewDubbingServiceDeleteRecordArgs() *DubbingServiceDeleteRecordArgs {
	return &DubbingServiceDeleteRecordArgs{}
}

func (p *DubbingServiceDeleteRecordArgs) InitDefault() {
}

var DubbingServiceDeleteRecordArgs_Req_DEFAULT *DeleteRecordReq

func (p *DubbingServiceDeleteRecordArgs) GetReq() (v *DeleteRecordReq) {
	if !p.IsSetReq() {
		return DubbingServiceDeleteRecordArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DubbingServiceDeleteRecordArgs) SetReq(val *DeleteRecordReq) {
	p.Req = val
}

func (p *DubbingServiceDeleteRecordArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DubbingServiceDeleteRecordArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DubbingServiceDeleteRecordArgs(%+v)", *p)
}

var fieldIDToName_DubbingServiceDeleteRecordArgs = map[int16]string{
	1: "req",
}

type DubbingServiceDeleteRecordResult struct {
	Success *bool `thrift:"success,0,optional" frugal:"0,optional,bool" json:"success,omitempty"`
}

func NewDubbingServiceDeleteRecordResult() *DubbingServiceDeleteRecordResult {
	return &DubbingServiceDeleteRecordResult{}
}

func (p *DubbingServiceDeleteRecordResult) InitDefault() {
}

var DubbingServiceDeleteRecordResult_Success_DEFAULT bool

func (p *DubbingServiceDeleteRecordResult) GetSuccess() (v bool) {
	if !p.IsSetSuccess() {
		return DubbingServiceDeleteRecordResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *DubbingServiceDeleteRecordResult) SetSuccess(x interface{}) {
	p.Success = x.(*bool)
}

func (p *DubbingServiceDeleteRecordResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DubbingServiceDeleteRecordResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DubbingServiceDeleteRecordResult(%+v)", *p)
}

var fieldIDToName_DubbingServiceDeleteRecordResult = map[int16]string{
	0: "success",
}
