// Code generated by Kitex v0.16.3. DO NOT EDIT.

package dubbingservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	dubbing "parrot-backend-go/kitex_gen/dubbing"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetOptions(ctx context.Context, req *dubbing.GetOptionsReq, callOptions ...callopt.Option) (r *dubbing.OptionsResp, err error)
	GenerateDraft(ctx context.Context, req *dubbing.GenerateDraftReq, callOptions ...callopt.Option) (r *dubbing.TaskCreatedResp, err error)
	CreatePreview(ctx context.Context, req *dubbing.PreviewReq, callOptions ...callopt.Option) (r *dubbing.TaskCreatedResp, err error)
	CreateExport(ctx context.Context, req *dubbing.ExportReq, callOptions ...callopt.Option) (r *dubbing.TaskCreatedResp, err error)
	GetRecords(ctx context.Context, req *dubbing.GetRecordsReq, callOptions ...callopt.Option) (r *dubbing.RecordsResp, err error)
	DeleteRecord(ctx context.Context, req *dubbing.DeleteRecordReq, callOptions ...callopt.Option) (r bool, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kDubbingServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kDubbingServiceClient struct {
	*kClient
}

func (p *kDubbingServiceClient) GetOptions(ctx context.Context, req *dubbing.GetOptionsReq, callOptions ...callopt.Option) (r *dubbing.OptionsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOptions(ctx, req)
}

func (p *kDubbingServiceClient) GenerateDraft(ctx context.Context, req *dubbing.GenerateDraftReq, callOptions ...callopt.Option) (r *dubbing.TaskCreatedResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GenerateDraft(ctx, req)
}

func (p *kDubbingServiceClient) CreatePreview(ctx context.Context, req *dubbing.PreviewReq, callOptions ...callopt.Option) (r *dubbing.TaskCreatedResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreatePreview(ctx, req)
}

func (p *kDubbingServiceClient) CreateExport(ctx context.Context, req *dubbing.ExportReq, callOptions ...callopt.Option) (r *dubbing.TaskCreatedResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateExport(ctx, req)
}

func (p *kDubbingServiceClient) GetRecords(ctx context.Context, req *dubbing.GetRecordsReq, callOptions ...callopt.Option) (r *dubbing.RecordsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRecords(ctx, req)
}

func (p *kDubbingServiceClient) DeleteRecord(ctx context.Context, req *dubbing.DeleteRecordReq, callOptions ...callopt.Option) (r bool, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteRecord(ctx, req)
}
