// Code generated by Kitex v0.16.3. DO NOT EDIT.

package dubbingservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	dubbing "parrot-backend-go/kitex_gen/dubbing"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetOptions": kitex.NewMethodInfo(
		getOptionsHandler,
		newDubbingServiceGetOptionsArgs,
		newDubbingServiceGetOptionsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GenerateDraft": kitex.NewMethodInfo(
		generateDraftHandler,
		newDubbingServiceGenerateDraftArgs,
		newDubbingServiceGenerateDraftResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreatePreview": kitex.NewMethodInfo(
		createPreviewHandler,
		newDubbingServiceCreatePreviewArgs,
		newDubbingServiceCreatePreviewResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateExport": kitex.NewMethodInfo(
		createExportHandler,
		newDubbingServiceCreateExportArgs,
		newDubbingServiceCreateExportResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetRecords": kitex.NewMethodInfo(
		getRecordsHandler,
		newDubbingServiceGetRecordsArgs,
		newDubbingServiceGetRecordsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteRecord": kitex.NewMethodInfo(
		deleteRecordHandler,
		newDubbingServiceDeleteRecordArgs,
		newDubbingServiceDeleteRecordResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	dubbingServiceServiceInfo                = NewServiceInfo()
	dubbingServiceServiceInfoForClient       = NewServiceInfoForClient()
	dubbingServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return dubbingServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return dubbingServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return dubbingServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "DubbingService"
	handlerType := (*dubbing.DubbingService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "dubbing",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func getOptionsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*dubbing.DubbingServiceGetOptionsArgs)
	realResult := result.(*dubbing.DubbingServiceGetOptionsResult)
	success, err := handler.(dubbing.DubbingService).GetOptions(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDubbingServiceGetOptionsArgs() interface{} {
	return dubbing.NewDubbingServiceGetOptionsArgs()
}

func newDubbingServiceGetOptionsResult() interface{} {
	return dubbing.NewDubbingServiceGetOptionsResult()
}

func generateDraftHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*dubbing.DubbingServiceGenerateDraftArgs)
	realResult := result.(*dubbing.DubbingServiceGenerateDraftResult)
	success, err := handler.(dubbing.DubbingService).GenerateDraft(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDubbingServiceGenerateDraftArgs() interface{} {
	return dubbing.NewDubbingServiceGenerateDraftArgs()
}

func newDubbingServiceGenerateDraftResult() interface{} {
	return dubbing.NewDubbingServiceGenerateDraftResult()
}

func createPreviewHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*dubbing.DubbingServiceCreatePreviewArgs)
	realResult := result.(*dubbing.DubbingServiceCreatePreviewResult)
	success, err := handler.(dubbing.DubbingService).CreatePreview(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDubbingServiceCreatePreviewArgs() interface{} {
	return dubbing.NewDubbingServiceCreatePreviewArgs()
}

func newDubbingServiceCreatePreviewResult() interface{} {
	return dubbing.NewDubbingServiceCreatePreviewResult()
}

func createExportHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*dubbing.DubbingServiceCreateExportArgs)
	realResult := result.(*dubbing.DubbingServiceCreateExportResult)
	success, err := handler.(dubbing.DubbingService).CreateExport(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDubbingServiceCreateExportArgs() interface{} {
	return dubbing.NewDubbingServiceCreateExportArgs()
}

func newDubbingServiceCreateExportResult() interface{} {
	return dubbing.NewDubbingServiceCreateExportResult()
}

func getRecordsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*dubbing.DubbingServiceGetRecordsArgs)
	realResult := result.(*dubbing.DubbingServiceGetRecordsResult)
	success, err := handler.(dubbing.DubbingService).GetRecords(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDubbingServiceGetRecordsArgs() interface{} {
	return dubbing.NewDubbingServiceGetRecordsArgs()
}

func newDubbingServiceGetRecordsResult() interface{} {
	return dubbing.NewDubbingServiceGetRecordsResult()
}

func deleteRecordHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*dubbing.DubbingServiceDeleteRecordArgs)
	realResult := result.(*dubbing.DubbingServiceDeleteRecordResult)
	success, err := handler.(dubbing.DubbingService).DeleteRecord(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newDubbingServiceDeleteRecordArgs() interface{} {
	return dubbing.NewDubbingServiceDeleteRecordArgs()
}

func newDubbingServiceDeleteRecordResult() interface{} {
	return dubbing.NewDubbingServiceDeleteRecordResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetOptions(ctx context.Context, req *dubbing.GetOptionsReq) (r *dubbing.OptionsResp, err error) {
	var _args dubbing.DubbingServiceGetOptionsArgs
	_args.Req = req
	var _result dubbing.DubbingServiceGetOptionsResult
	if err = p.c.Call(ctx, "GetOptions", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GenerateDraft(ctx context.Context, req *dubbing.GenerateDraftReq) (r *dubbing.TaskCreatedResp, err error) {
	var _args dubbing.DubbingServiceGenerateDraftArgs
	_args.Req = req
	var _result dubbing.DubbingServiceGenerateDraftResult
	if err = p.c.Call(ctx, "GenerateDraft", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreatePreview(ctx context.Context, req *dubbing.PreviewReq) (r *dubbing.TaskCreatedResp, err error) {
	var _args dubbing.DubbingServiceCreatePreviewArgs
	_args.Req = req
	var _result dubbing.DubbingServiceCreatePreviewResult
	if err = p.c.Call(ctx, "CreatePreview", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateExport(ctx context.Context, req *dubbing.ExportReq) (r *dubbing.TaskCreatedResp, err error) {
	var _args dubbing.DubbingServiceCreateExportArgs
	_args.Req = req
	var _result dubbing.DubbingServiceCreateExportResult
	if err = p.c.Call(ctx, "CreateExport", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetRecords(ctx context.Context, req *dubbing.GetRecordsReq) (r *dubbing.RecordsResp, err error) {
	var _args dubbing.DubbingServiceGetRecordsArgs
	_args.Req = req
	var _result dubbing.DubbingServiceGetRecordsResult
	if err = p.c.Call(ctx, "GetRecords", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteRecord(ctx context.Context, req *dubbing.DeleteRecordReq) (r bool, err error) {
	var _args dubbing.DubbingServiceDeleteRecordArgs
	_args.Req = req
	var _result dubbing.DubbingServiceDeleteRecordResult
	if err = p.c.Call(ctx, "DeleteRecord", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
