// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package user

import (
	"context"
	"fmt"
)

type User struct {
	Id              int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Email           string `thrift:"email,2" frugal:"2,default,string" json:"email"`
	Username        string `thrift:"username,3" frugal:"3,default,string" json:"username"`
	Phone           string `thrift:"phone,4" frugal:"4,default,string" json:"phone"`
	Age             string `thrift:"age,5" frugal:"5,default,string" json:"age"`
	Gender          string `thrift:"gender,6" frugal:"6,default,string" json:"gender"`
	AvatarUrl       string `thrift:"avatarUrl,7" frugal:"7,default,string" json:"avatarUrl"`
	SecurityAnswers []byte `thrift:"securityAnswers,8" frugal:"8,default,binary" json:"securityAnswers"`
	Role            string `thrift:"role,9" frugal:"9,default,string" json:"role"`
	Status          string `thrift:"status,10" frugal:"10,default,string" json:"status"`
	CreatedAt       string `thrift:"createdAt,11" frugal:"11,default,string" json:"createdAt"`
}

func NewUser() *User {
	return &User{}
}

func (p *User) InitDefault() {
}

func (p *User) GetId() (v int64) {
	return p.Id
}

func (p *User) GetEmail() (v string) {
	return p.Email
}

func (p *User) GetUsername() (v string) {
	return p.Username
}

func (p *User) GetPhone() (v string) {
	return p.Phone
}

func (p *User) GetAge() (v string) {
	return p.Age
}

func (p *User) GetGender() (v string) {
	return p.Gender
}

func (p *User) GetAvatarUrl() (v string) {
	return p.AvatarUrl
}

func (p *User) GetSecurityAnswers() (v []byte) {
	return p.SecurityAnswers
}

func (p *User) GetRole() (v string) {
	return p.Role
}

func (p *User) GetStatus() (v string) {
	return p.Status
}

func (p *User) GetCreatedAt() (v string) {
	return p.CreatedAt
}
func (p *User) SetId(val int64) {
	p.Id = val
}
func (p *User) SetEmail(val string) {
	p.Email = val
}
func (p *User) SetUsername(val string) {
	p.Username = val
}
func (p *User) SetPhone(val string) {
	p.Phone = val
}
func (p *User) SetAge(val string) {
	p.Age = val
}
func (p *User) SetGender(val string) {
	p.Gender = val
}
func (p *User) SetAvatarUrl(val string) {
	p.AvatarUrl = val
}
func (p *User) SetSecurityAnswers(val []byte) {
	p.SecurityAnswers = val
}
func (p *User) SetRole(val string) {
	p.Role = val
}
func (p *User) SetStatus(val string) {
	p.Status = val
}
func (p *User) SetCreatedAt(val string) {
	p.CreatedAt = val
}

func (p *User) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("User(%+v)", *p)
}

var fieldIDToName_User = map[int16]string{
	1:  "id",
	2:  "email",
	3:  "username",
	4:  "phone",
	5:  "age",
	6:  "gender",
	7:  "avatarUrl",
	8:  "securityAnswers",
	9:  "role",
	10: "status",
	11: "createdAt",
}

type AuthResp struct {
	Token string `thrift:"token,1" frugal:"1,default,string" json:"token"`
	User  *User  `thrift:"user,2" frugal:"2,default,User" json:"user"`
}

func NewAuthResp() *AuthResp {
	return &AuthResp{}
}

func (p *AuthResp) InitDefault() {
}

func (p *AuthResp) GetToken() (v string) {
	return p.Token
}

var AuthResp_User_DEFAULT *User

func (p *AuthResp) GetUser() (v *User) {
	if !p.IsSetUser() {
		return AuthResp_User_DEFAULT
	}
	return p.User
}
func (p *AuthResp) SetToken(val string) {
	p.Token = val
}
func (p *AuthResp) SetUser(val *User) {
	p.User = val
}

func (p *AuthResp) IsSetUser() bool {
	return p.User != nil
}

func (p *AuthResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthResp(%+v)", *p)
}

var fieldIDToName_AuthResp = map[int16]string{
	1: "token",
	2: "user",
}

type SendCodeResp struct {
	Email     string  `thrift:"email,1" frugal:"1,default,string" json:"email"`
	ExpiresAt string  `thrift:"expiresAt,2" frugal:"2,default,string" json:"expiresAt"`
	DevMode   bool    `thrift:"devMode,3" frugal:"3,default,bool" json:"devMode"`
	Code      *string `thrift:"code,4,optional" frugal:"4,optional,string" json:"code,omitempty"`
}

func NewSendCodeResp() *SendCodeResp {
	return &SendCodeResp{}
}

func (p *SendCodeResp) InitDefault() {
}

func (p *SendCodeResp) GetEmail() (v string) {
	return p.Email
}

func (p *SendCodeResp) GetExpiresAt() (v string) {
	return p.ExpiresAt
}

func (p *SendCodeResp) GetDevMode() (v bool) {
	return p.DevMode
}

var SendCodeResp_Code_DEFAULT string

func (p *SendCodeResp) GetCode() (v string) {
	if !p.IsSetCode() {
		return SendCodeResp_Code_DEFAULT
	}
	return *p.Code
}
func (p *SendCodeResp) SetEmail(val string) {
	p.Email = val
}
func (p *SendCodeResp) SetExpiresAt(val string) {
	p.ExpiresAt = val
}
func (p *SendCodeResp) SetDevMode(val bool) {
	p.DevMode = val
}
func (p *SendCodeResp) SetCode(val *string) {
	p.Code = val
}

func (p *SendCodeResp) IsSetCode() bool {
	return p.Code != nil
}

func (p *SendCodeResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendCodeResp(%+v)", *p)
}

var fieldIDToName_SendCodeResp = map[int16]string{
	1: "email",
	2: "expiresAt",
	3: "devMode",
	4: "code",
}

type Notification struct {
	Id        int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	UserId    int64  `thrift:"userId,2" frugal:"2,default,i64" json:"userId"`
	Type      string `thrift:"type,3" frugal:"3,default,string" json:"type"`
	Title     string `thrift:"title,4" frugal:"4,default,string" json:"title"`
	Desc      string `thrift:"desc,5" frugal:"5,default,string" json:"desc"`
	IsRead    bool   `thrift:"isRead,6" frugal:"6,default,bool" json:"isRead"`
	EventId   string `thrift:"eventId,7" frugal:"7,default,string" json:"eventId"`
	CreatedAt string `thrift:"createdAt,8" frugal:"8,default,string" json:"createdAt"`
}

func NewNotification() *Notification {
	return &Notification{}
}

func (p *Notification) InitDefault() {
}

func (p *Notification) GetId() (v int64) {
	return p.Id
}

func (p *Notification) GetUserId() (v int64) {
	return p.UserId
}

func (p *Notification) GetType() (v string) {
	return p.Type
}

func (p *Notification) GetTitle() (v string) {
	return p.Title
}

func (p *Notification) GetDesc() (v string) {
	return p.Desc
}

func (p *Notification) GetIsRead() (v bool) {
	return p.IsRead
}

func (p *Notification) GetEventId() (v string) {
	return p.EventId
}

func (p *Notification) GetCreatedAt() (v string) {
	return p.CreatedAt
}
func (p *Notification) SetId(val int64) {
	p.Id = val
}
func (p *Notification) SetUserId(val int64) {
	p.UserId = val
}
func (p *Notification) SetType(val string) {
	p.Type = val
}
func (p *Notification) SetTitle(val string) {
	p.Title = val
}
func (p *Notification) SetDesc(val string) {
	p.Desc = val
}
func (p *Notification) SetIsRead(val bool) {
	p.IsRead = val
}
func (p *Notification) SetEventId(val string) {
	p.EventId = val
}
func (p *Notification) SetCreatedAt(val string) {
	p.CreatedAt = val
}

func (p *Notification) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Notification(%+v)", *p)
}

var fieldIDToName_Notification = map[int16]string{
	1: "id",
	2: "userId",
	3: "type",
	4: "title",
	5: "desc",
	6: "isRead",
	7: "eventId",
	8: "createdAt",
}

type Interaction struct {
	Id        int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	UserId    int64  `thrift:"userId,2" frugal:"2,default,i64" json:"userId"`
	ActorId   int64  `thrift:"actorId,3" frugal:"3,default,i64" json:"actorId"`
	VoiceId   int64  `thrift:"voiceId,4" frugal:"4,default,i64" json:"voiceId"`
	Type      string `thrift:"type,5" frugal:"5,default,string" json:"type"`
	CreatedAt string `thrift:"createdAt,6" frugal:"6,default,string" json:"createdAt"`
}

func NewInteraction() *Interaction {
	return &Interaction{}
}

func (p *Interaction) InitDefault() {
}

func (p *Interaction) GetId() (v int64) {
	return p.Id
}

func (p *Interaction) GetUserId() (v int64) {
	return p.UserId
}

func (p *Interaction) GetActorId() (v int64) {
	return p.ActorId
}

func (p *Interaction) GetVoiceId() (v int64) {
	return p.VoiceId
}

func (p *Interaction) GetType() (v string) {
	return p.Type
}

func (p *Interaction) GetCreatedAt() (v string) {
	return p.CreatedAt
}
func (p *Interaction) SetId(val int64) {
	p.Id = val
}
func (p *Interaction) SetUserId(val int64) {
	p.UserId = val
}
func (p *Interaction) SetActorId(val int64) {
	p.ActorId = val
}
func (p *Interaction) SetVoiceId(val int64) {
	p.VoiceId = val
}
func (p *Interaction) SetType(val string) {
	p.Type = val
}
func (p *Interaction) SetCreatedAt(val string) {
	p.CreatedAt = val
}

func (p *Interaction) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Interaction(%+v)", *p)
}

var fieldIDToName_Interaction = map[int16]string{
	1: "id",
	2: "userId",
	3: "actorId",
	4: "voiceId",
	5: "type",
	6: "createdAt",
}

type PaginatedResp struct {
	Items    []byte `thrift:"items,1" frugal:"1,default,binary" json:"items"`
	Total    int64  `thrift:"total,2" frugal:"2,default,i64" json:"total"`
	Page     int32  `thrift:"page,3" frugal:"3,default,i32" json:"page"`
	PageSize int32  `thrift:"pageSize,4" frugal:"4,default,i32" json:"pageSize"`
}

func NewPaginatedResp() *PaginatedResp {
	return &PaginatedResp{}
}

func (p *PaginatedResp) InitDefault() {
}

func (p *PaginatedResp) GetItems() (v []byte) {
	return p.Items
}

func (p *PaginatedResp) GetTotal() (v int64) {
	return p.Total
}

func (p *PaginatedResp) GetPage() (v int32) {
	return p.Page
}

func (p *PaginatedResp) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *PaginatedResp) SetItems(val []byte) {
	p.Items = val
}
func (p *PaginatedResp) SetTotal(val int64) {
	p.Total = val
}
func (p *PaginatedResp) SetPage(val int32) {
	p.Page = val
}
func (p *PaginatedResp) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *PaginatedResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PaginatedResp(%+v)", *p)
}

var fieldIDToName_PaginatedResp = map[int16]string{
	1: "items",
	2: "total",
	3: "page",
	4: "pageSize",
}

type LoginReq struct {
	Email    string `thrift:"email,1" frugal:"1,default,string" json:"email"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
}

func NewLoginReq() *LoginReq {
	return &LoginReq{}
}

func (p *LoginReq) InitDefault() {
}

func (p *LoginReq) GetEmail() (v string) {
	return p.Email
}

func (p *LoginReq) GetPassword() (v string) {
	return p.Password
}
func (p *LoginReq) SetEmail(val string) {
	p.Email = val
}
func (p *LoginReq) SetPassword(val string) {
	p.Password = val
}

func (p *LoginReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginReq(%+v)", *p)
}

var fieldIDToName_LoginReq = map[int16]string{
	1: "email",
	2: "password",
}

type RegisterReq struct {
	Email    string `thrift:"email,1" frugal:"1,default,string" json:"email"`
	Username string `thrift:"username,2" frugal:"2,default,string" json:"username"`
	Password string `thrift:"password,3" frugal:"3,default,string" json:"password"`
	Code     string `thrift:"code,4" frugal:"4,default,string" json:"code"`
}

func NewRegisterReq() *RegisterReq {
	return &RegisterReq{}
}

func (p *RegisterReq) InitDefault() {
}

func (p *RegisterReq) GetEmail() (v string) {
	return p.Email
}

func (p *RegisterReq) GetUsername() (v string) {
	return p.Username
}

func (p *RegisterReq) GetPassword() (v string) {
	return p.Password
}

func (p *RegisterReq) GetCode() (v string) {
	return p.Code
}
func (p *RegisterReq) SetEmail(val string) {
	p.Email = val
}
func (p *RegisterReq) SetUsername(val string) {
	p.Username = val
}
func (p *RegisterReq) SetPassword(val string) {
	p.Password = val
}
func (p *RegisterReq) SetCode(val string) {
	p.Code = val
}

func (p *RegisterReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterReq(%+v)", *p)
}

var fieldIDToName_RegisterReq = map[int16]string{
	1: "email",
	2: "username",
	3: "password",
	4: "code",
}

type ResetPasswordReq struct {
	Email    string `thrift:"email,1" frugal:"1,default,string" json:"email"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
	Code     string `thrift:"code,3" frugal:"3,default,string" json:"code"`
}

func NewResetPasswordReq() *ResetPasswordReq {
	return &ResetPasswordReq{}
}

func (p *ResetPasswordReq) InitDefault() {
}

func (p *ResetPasswordReq) GetEmail() (v string) {
	return p.Email
}

func (p *ResetPasswordReq) GetPassword() (v string) {
	return p.Password
}

func (p *ResetPasswordReq) GetCode() (v string) {
	return p.Code
}
func (p *ResetPasswordReq) SetEmail(val string) {
	p.Email = val
}
func (p *ResetPasswordReq) SetPassword(val string) {
	p.Password = val
}
func (p *ResetPasswordReq) SetCode(val string) {
	p.Code = val
}

func (p *ResetPasswordReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ResetPasswordReq(%+v)", *p)
}

var fieldIDToName_ResetPasswordReq = map[int16]string{
	1: "email",
	2: "password",
	3: "code",
}

type UpdateProfileReq struct {
	UserId    int64   `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	Username  *string `thrift:"username,2,optional" frugal:"2,optional,string" json:"username,omitempty"`
	Phone     *string `thrift:"phone,3,optional" frugal:"3,optional,string" json:"phone,omitempty"`
	Age       *string `thrift:"age,4,optional" frugal:"4,optional,string" json:"age,omitempty"`
	Gender    *string `thrift:"gender,5,optional" frugal:"5,optional,string" json:"gender,omitempty"`
	AvatarUrl *string `thrift:"avatarUrl,6,optional" frugal:"6,optional,string" json:"avatarUrl,omitempty"`
}

func NewUpdateProfileReq() *UpdateProfileReq {
	return &UpdateProfileReq{}
}

func (p *UpdateProfileReq) InitDefault() {
}

func (p *UpdateProfileReq) GetUserId() (v int64) {
	return p.UserId
}

var UpdateProfileReq_Username_DEFAULT string

func (p *UpdateProfileReq) GetUsername() (v string) {
	if !p.IsSetUsername() {
		return UpdateProfileReq_Username_DEFAULT
	}
	return *p.Username
}

var UpdateProfileReq_Phone_DEFAULT string

func (p *UpdateProfileReq) GetPhone() (v string) {
	if !p.IsSetPhone() {
		return UpdateProfileReq_Phone_DEFAULT
	}
	return *p.Phone
}

var UpdateProfileReq_Age_DEFAULT string

func (p *UpdateProfileReq) GetAge() (v string) {
	if !p.IsSetAge() {
		return UpdateProfileReq_Age_DEFAULT
	}
	return *p.Age
}

var UpdateProfileReq_Gender_DEFAULT string

func (p *UpdateProfileReq) GetGender() (v string) {
	if !p.IsSetGender() {
		return UpdateProfileReq_Gender_DEFAULT
	}
	return *p.Gender
}

var UpdateProfileReq_AvatarUrl_DEFAULT string

func (p *UpdateProfileReq) GetAvatarUrl() (v string) {
	if !p.IsSetAvatarUrl() {
		return UpdateProfileReq_AvatarUrl_DEFAULT
	}
	return *p.AvatarUrl
}
func (p *UpdateProfileReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *UpdateProfileReq) SetUsername(val *string) {
	p.Username = val
}
func (p *UpdateProfileReq) SetPhone(val *string) {
	p.Phone = val
}
func (p *UpdateProfileReq) SetAge(val *string) {
	p.Age = val
}
func (p *UpdateProfileReq) SetGender(val *string) {
	p.Gender = val
}
func (p *UpdateProfileReq) SetAvatarUrl(val *string) {
	p.AvatarUrl = val
}

func (p *UpdateProfileReq) IsSetUsername() bool {
	return p.Username != nil
}

func (p *UpdateProfileReq) IsSetPhone() bool {
	return p.Phone != nil
}

func (p *UpdateProfileReq) IsSetAge() bool {
	return p.Age != nil
}

func (p *UpdateProfileReq) IsSetGender() bool {
	return p.Gender != nil
}

func (p *UpdateProfileReq) IsSetAvatarUrl() bool {
	return p.AvatarUrl != nil
}

func (p *UpdateProfileReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateProfileReq(%+v)", *p)
}

var fieldIDToName_UpdateProfileReq = map[int16]string{
	1: "userId",
	2: "username",
	3: "phone",
	4: "age",
	5: "gender",
	6: "avatarUrl",
}

type UpdatePasswordReq struct {
	UserId          int64   `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	Q1              *string `thrift:"q1,2,optional" frugal:"2,optional,string" json:"q1,omitempty"`
	Q2              *string `thrift:"q2,3,optional" frugal:"3,optional,string" json:"q2,omitempty"`
	Q3              *string `thrift:"q3,4,optional" frugal:"4,optional,string" json:"q3,omitempty"`
	Password        string  `thrift:"password,5" frugal:"5,default,string" json:"password"`
	ConfirmPassword string  `thrift:"confirmPassword,6" frugal:"6,default,string" json:"confirmPassword"`
}

func NewUpdatePasswordReq() *UpdatePasswordReq {
	return &UpdatePasswordReq{}
}

func (p *UpdatePasswordReq) InitDefault() {
}

func (p *UpdatePasswordReq) GetUserId() (v int64) {
	return p.UserId
}

var UpdatePasswordReq_Q1_DEFAULT string

func (p *UpdatePasswordReq) GetQ1() (v string) {
	if !p.IsSetQ1() {
		return UpdatePasswordReq_Q1_DEFAULT
	}
	return *p.Q1
}

var UpdatePasswordReq_Q2_DEFAULT string

func (p *UpdatePasswordReq) GetQ2() (v string) {
	if !p.IsSetQ2() {
		return UpdatePasswordReq_Q2_DEFAULT
	}
	return *p.Q2
}

var UpdatePasswordReq_Q3_DEFAULT string

func (p *UpdatePasswordReq) GetQ3() (v string) {
	if !p.IsSetQ3() {
		return UpdatePasswordReq_Q3_DEFAULT
	}
	return *p.Q3
}

func (p *UpdatePasswordReq) GetPassword() (v string) {
	return p.Password
}

func (p *UpdatePasswordReq) GetConfirmPassword() (v string) {
	return p.ConfirmPassword
}
func (p *UpdatePasswordReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *UpdatePasswordReq) SetQ1(val *string) {
	p.Q1 = val
}
func (p *UpdatePasswordReq) SetQ2(val *string) {
	p.Q2 = val
}
func (p *UpdatePasswordReq) SetQ3(val *string) {
	p.Q3 = val
}
func (p *UpdatePasswordReq) SetPassword(val string) {
	p.Password = val
}
func (p *UpdatePasswordReq) SetConfirmPassword(val string) {
	p.ConfirmPassword = val
}

func (p *UpdatePasswordReq) IsSetQ1() bool {
	return p.Q1 != nil
}

func (p *UpdatePasswordReq) IsSetQ2() bool {
	return p.Q2 != nil
}

func (p *UpdatePasswordReq) IsSetQ3() bool {
	return p.Q3 != nil
}

func (p *UpdatePasswordReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdatePasswordReq(%+v)", *p)
}

var fieldIDToName_UpdatePasswordReq = map[int16]string{
	1: "userId",
	2: "q1",
	3: "q2",
	4: "q3",
	5: "password",
	6: "confirmPassword",
}

type CreateNotificationReq struct {
	UserId  int64  `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	Type    string `thrift:"type,2" frugal:"2,default,string" json:"type"`
	Title   string `thrift:"title,3" frugal:"3,default,string" json:"title"`
	Desc    string `thrift:"desc,4" frugal:"4,default,string" json:"desc"`
	EventId string `thrift:"eventId,5" frugal:"5,default,string" json:"eventId"`
}

func NewCreateNotificationReq() *CreateNotificationReq {
	return &CreateNotificationReq{}
}

func (p *CreateNotificationReq) InitDefault() {
}

func (p *CreateNotificationReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *CreateNotificationReq) GetType() (v string) {
	return p.Type
}

func (p *CreateNotificationReq) GetTitle() (v string) {
	return p.Title
}

func (p *CreateNotificationReq) GetDesc() (v string) {
	return p.Desc
}

func (p *CreateNotificationReq) GetEventId() (v string) {
	return p.EventId
}
func (p *CreateNotificationReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *CreateNotificationReq) SetType(val string) {
	p.Type = val
}
func (p *CreateNotificationReq) SetTitle(val string) {
	p.Title = val
}
func (p *CreateNotificationReq) SetDesc(val string) {
	p.Desc = val
}
func (p *CreateNotificationReq) SetEventId(val string) {
	p.EventId = val
}

func (p *CreateNotificationReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateNotificationReq(%+v)", *p)
}

var fieldIDToName_CreateNotificationReq = map[int16]string{
	1: "userId",
	2: "type",
	3: "title",
	4: "desc",
	5: "eventId",
}

type CreateInteractionReq struct {
	UserId  int64  `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	ActorId int64  `thrift:"actorId,2" frugal:"2,default,i64" json:"actorId"`
	VoiceId int64  `thrift:"voiceId,3" frugal:"3,default,i64" json:"voiceId"`
	Type    string `thrift:"type,4" frugal:"4,default,string" json:"type"`
}

func NewCreateInteractionReq() *CreateInteractionReq {
	return &CreateInteractionReq{}
}

func (p *CreateInteractionReq) InitDefault() {
}

func (p *CreateInteractionReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *CreateInteractionReq) GetActorId() (v int64) {
	return p.ActorId
}

func (p *CreateInteractionReq) GetVoiceId() (v int64) {
	return p.VoiceId
}

func (p *CreateInteractionReq) GetType() (v string) {
	return p.Type
}
func (p *CreateInteractionReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *CreateInteractionReq) SetActorId(val int64) {
	p.ActorId = val
}
func (p *CreateInteractionReq) SetVoiceId(val int64) {
	p.VoiceId = val
}
func (p *CreateInteractionReq) SetType(val string) {
	p.Type = val
}

func (p *CreateInteractionReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateInteractionReq(%+v)", *p)
}

var fieldIDToName_CreateInteractionReq = map[int16]string{
	1: "userId",
	2: "actorId",
	3: "voiceId",
	4: "type",
}

type GetListReq struct {
	UserId   int64  `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	Type     string `thrift:"type,2" frugal:"2,default,string" json:"type"`
	Page     int32  `thrift:"page,3" frugal:"3,default,i32" json:"page"`
	PageSize int32  `thrift:"pageSize,4" frugal:"4,default,i32" json:"pageSize"`
}

func NewGetListReq() *GetListReq {
	return &GetListReq{}
}

func (p *GetListReq) InitDefault() {
}

func (p *GetListReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *GetListReq) GetType() (v string) {
	return p.Type
}

func (p *GetListReq) GetPage() (v int32) {
	return p.Page
}

func (p *GetListReq) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *GetListReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *GetListReq) SetType(val string) {
	p.Type = val
}
func (p *GetListReq) SetPage(val int32) {
	p.Page = val
}
func (p *GetListReq) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *GetListReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetListReq(%+v)", *p)
}

var fieldIDToName_GetListReq = map[int16]string{
	1: "userId",
	2: "type",
	3: "page",
	4: "pageSize",
}

type AdminListUsersReq struct {
	Search   string `thrift:"search,1" frugal:"1,default,string" json:"search"`
	Status   string `thrift:"status,2" frugal:"2,default,string" json:"status"`
	Page     int32  `thrift:"page,3" frugal:"3,default,i32" json:"page"`
	PageSize int32  `thrift:"pageSize,4" frugal:"4,default,i32" json:"pageSize"`
}

func NewAdminListUsersReq() *AdminListUsersReq {
	return &AdminListUsersReq{}
}

func (p *AdminListUsersReq) InitDefault() {
}

func (p *AdminListUsersReq) GetSearch() (v string) {
	return p.Search
}

func (p *AdminListUsersReq) GetStatus() (v string) {
	return p.Status
}

func (p *AdminListUsersReq) GetPage() (v int32) {
	return p.Page
}

func (p *AdminListUsersReq) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *AdminListUsersReq) SetSearch(val string) {
	p.Search = val
}
func (p *AdminListUsersReq) SetStatus(val string) {
	p.Status = val
}
func (p *AdminListUsersReq) SetPage(val int32) {
	p.Page = val
}
func (p *AdminListUsersReq) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *AdminListUsersReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdminListUsersReq(%+v)", *p)
}

var fieldIDToName_AdminListUsersReq = map[int16]string{
	1: "search",
	2: "status",
	3: "page",
	4: "pageSize",
}

type AdminUpdateUserReq struct {
	Id        int64   `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Username  *string `thrift:"username,2,optional" frugal:"2,optional,string" json:"username,omitempty"`
	Phone     *string `thrift:"phone,3,optional" frugal:"3,optional,string" json:"phone,omitempty"`
	Age       *string `thrift:"age,4,optional" frugal:"4,optional,string" json:"age,omitempty"`
	Gender    *string `thrift:"gender,5,optional" frugal:"5,optional,string" json:"gender,omitempty"`
	AvatarUrl *string `thrift:"avatarUrl,6,optional" frugal:"6,optional,string" json:"avatarUrl,omitempty"`
	Status    *string `thrift:"status,7,optional" frugal:"7,optional,string" json:"status,omitempty"`
	Role      *string `thrift:"role,8,optional" frugal:"8,optional,string" json:"role,omitempty"`
}

func NewAdminUpdateUserReq() *AdminUpdateUserReq {
	return &AdminUpdateUserReq{}
}

func (p *AdminUpdateUserReq) InitDefault() {
}

func (p *AdminUpdateUserReq) GetId() (v int64) {
	return p.Id
}

var AdminUpdateUserReq_Username_DEFAULT string

func (p *AdminUpdateUserReq) GetUsername() (v string) {
	if !p.IsSetUsername() {
		return AdminUpdateUserReq_Username_DEFAULT
	}
	return *p.Username
}

var AdminUpdateUserReq_Phone_DEFAULT string

func (p *AdminUpdateUserReq) GetPhone() (v string) {
	if !p.IsSetPhone() {
		return AdminUpdateUserReq_Phone_DEFAULT
	}
	return *p.Phone
}

var AdminUpdateUserReq_Age_DEFAULT string

func (p *AdminUpdateUserReq) GetAge() (v string) {
	if !p.IsSetAge() {
		return AdminUpdateUserReq_Age_DEFAULT
	}
	return *p.Age
}

var AdminUpdateUserReq_Gender_DEFAULT string

func (p *AdminUpdateUserReq) GetGender() (v string) {
	if !p.IsSetGender() {
		return AdminUpdateUserReq_Gender_DEFAULT
	}
	return *p.Gender
}

var AdminUpdateUserReq_AvatarUrl_DEFAULT string

func (p *AdminUpdateUserReq) GetAvatarUrl() (v string) {
	if !p.IsSetAvatarUrl() {
		return AdminUpdateUserReq_AvatarUrl_DEFAULT
	}
	return *p.AvatarUrl
}

var AdminUpdateUserReq_Status_DEFAULT string

func (p *AdminUpdateUserReq) GetStatus() (v string) {
	if !p.IsSetStatus() {
		return AdminUpdateUserReq_Status_DEFAULT
	}
	return *p.Status
}

var AdminUpdateUserReq_Role_DEFAULT string

func (p *AdminUpdateUserReq) GetRole() (v string) {
	if !p.IsSetRole() {
		return AdminUpdateUserReq_Role_DEFAULT
	}
	return *p.Role
}
func (p *AdminUpdateUserReq) SetId(val int64) {
	p.Id = val
}
func (p *AdminUpdateUserReq) SetUsername(val *string) {
	p.Username = val
}
func (p *AdminUpdateUserReq) SetPhone(val *string) {
	p.Phone = val
}
func (p *AdminUpdateUserReq) SetAge(val *string) {
	p.Age = val
}
func (p *AdminUpdateUserReq) SetGender(val *string) {
	p.Gender = val
}
func (p *AdminUpdateUserReq) SetAvatarUrl(val *string) {
	p.AvatarUrl = val
}
func (p *AdminUpdateUserReq) SetStatus(val *string) {
	p.Status = val
}
func (p *AdminUpdateUserReq) SetRole(val *string) {
	p.Role = val
}

func (p *AdminUpdateUserReq) IsSetUsername() bool {
	return p.Username != nil
}

func (p *AdminUpdateUserReq) IsSetPhone() bool {
	return p.Phone != nil
}

func (p *AdminUpdateUserReq) IsSetAge() bool {
	return p.Age != nil
}

func (p *AdminUpdateUserReq) IsSetGender() bool {
	return p.Gender != nil
}

func (p *AdminUpdateUserReq) IsSetAvatarUrl() bool {
	return p.AvatarUrl != nil
}

func (p *AdminUpdateUserReq) IsSetStatus() bool {
	return p.Status != nil
}

func (p *AdminUpdateUserReq) IsSetRole() bool {
	return p.Role != nil
}

func (p *AdminUpdateUserReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdminUpdateUserReq(%+v)", *p)
}

var fieldIDToName_AdminUpdateUserReq = map[int16]string{
	1: "id",
	2: "username",
	3: "phone",
	4: "age",
	5: "gender",
	6: "avatarUrl",
	7: "status",
	8: "role",
}

type BroadcastReq struct {
	Title string `thrift:"title,1" frugal:"1,default,string" json:"title"`
	Desc  string `thrift:"desc,2" frugal:"2,default,string" json:"desc"`
	Type  string `thrift:"type,3" frugal:"3,default,string" json:"type"`
}

func NewBroadcastReq() *BroadcastReq {
	return &BroadcastReq{}
}

func (p *BroadcastReq) InitDefault() {
}

func (p *BroadcastReq) GetTitle() (v string) {
	return p.Title
}

func (p *BroadcastReq) GetDesc() (v string) {
	return p.Desc
}

func (p *BroadcastReq) GetType() (v string) {
	return p.Type
}
func (p *BroadcastReq) SetTitle(val string) {
	p.Title = val
}
func (p *BroadcastReq) SetDesc(val string) {
	p.Desc = val
}
func (p *BroadcastReq) SetType(val string) {
	p.Type = val
}

func (p *BroadcastReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BroadcastReq(%+v)", *p)
}

var fieldIDToName_BroadcastReq = map[int16]string{
	1: "title",
	2: "desc",
	3: "type",
}

type UserService interface {
	SendCode(ctx context.Context, email string) (r *SendCodeResp, err error)

	Register(ctx context.Context, req *RegisterReq) (r *AuthResp, err error)

	Login(ctx context.Context, req *LoginReq) (r *AuthResp, err error)

	SocialLogin(ctx context.Context, provider string) (r *AuthResp, err error)

	ResetPassword(ctx context.Context, req *ResetPasswordReq) (r bool, err error)

	GetUserByID(ctx context.Context, id int64) (r *User, err error)

	GetUsersByIDs(ctx context.Context, ids []int64) (r []*User, err error)

	UpdateProfile(ctx context.Context, req *UpdateProfileReq) (r *User, err error)

	UpdatePassword(ctx context.Context, req *UpdatePasswordReq) (r bool, err error)

	GetNotifications(ctx context.Context, req *GetListReq) (r *PaginatedResp, err error)

	ReadNotification(ctx context.Context, userId int64, notifId int64) (r bool, err error)

	CreateNotification(ctx context.Context, req *CreateNotificationReq) (r bool, err error)

	GetInteractions(ctx context.Context, req *GetListReq) (r *PaginatedResp, err error)

	CreateInteraction(ctx context.Context, req *CreateInteractionReq) (r bool, err error)

	AdminListUsers(ctx context.Context, req *AdminListUsersReq) (r *PaginatedResp, err error)

	AdminGetUser(ctx context.Context, id int64) (r *User, err error)

	AdminUpdateUser(ctx context.Context, req *AdminUpdateUserReq) (r *User, err error)

	AdminDeleteUser(ctx context.Context, id int64) (r bool, err error)

	AdminBroadcast(ctx context.Context, req *BroadcastReq) (r int32, err error)

	CountAll(ctx context.Context) (r int64, err error)
}

type UserServiceSendCodeArgs struct {
	Email string `thrift:"email,1" frugal:"1,default,string" json:"email"`
}

func NewUserServiceSendCodeArgs() *UserServiceSendCodeArgs {
	return &UserServiceSendCodeArgs{}
}

func (p *UserServiceSendCodeArgs) InitDefault() {
}

func (p *UserServiceSendCodeArgs) GetEmail() (v string) {
	return p.Email
}
func (p *UserServiceSendCodeArgs) SetEmail(val string) {
	p.Email = val
}

func (p *UserServiceSendCodeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceSendCodeArgs(%+v)", *p)
}

var fieldIDToName_UserServiceSendCodeArgs = map[int16]string{
	1: "email",
}

type UserServiceSendCodeResult struct {
	Success *SendCodeResp `thrift:"success,0,optional" frugal:"0,optional,SendCodeResp" json:"success,omitempty"`
}

func NewUserServiceSendCodeResult() *UserServiceSendCodeResult {
	return &UserServiceSendCodeResult{}
}

func (p *UserServiceSendCodeResult) InitDefault() {
}

var UserServiceSendCodeResult_Success_DEFAULT *SendCodeResp

func (p *UserServiceSendCodeResult) GetSuccess() (v *SendCodeResp) {
	if !p.IsSetSuccess() {
		return UserServiceSendCodeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceSendCodeResult) SetSuccess(x interface{}) {
	p.Success = x.(*SendCodeResp)
}

func (p *UserServiceSendCodeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceSendCodeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceSendCodeResult(%+v)", *p)
}

var fieldIDToName_UserServiceSendCodeResult = map[int16]string{
	0: "success",
}

type UserServiceRegisterArgs struct {
	Req *RegisterReq `thrift:"req,1" frugal:"1,default,RegisterReq" json:"req"`
}

func NewUserServiceRegisterArgs() *UserServiceRegisterArgs {
	return &UserServiceRegisterArgs{}
}

func (p *UserServiceRegisterArgs) InitDefault() {
}

var UserServiceRegisterArgs_Req_DEFAULT *RegisterReq

func (p *UserServiceRegisterArgs) GetReq() (v *RegisterReq) {
	if !p.IsSetReq() {
		return UserServiceRegisterArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceRegisterArgs) SetReq(val *RegisterReq) {
	p.Req = val
}

func (p *UserServiceRegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceRegisterArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterArgs(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterArgs = map[int16]string{
	1: "req",
}

type UserServiceRegisterResult struct {
	Success *AuthResp `thrift:"success,0,optional" frugal:"0,optional,AuthResp" json:"success,omitempty"`
}

func NewUserServiceRegisterResult() *UserServiceRegisterResult {
	return &UserServiceRegisterResult{}
}

func (p *UserServiceRegisterResult) InitDefault() {
}

var UserServiceRegisterResult_Success_DEFAULT *AuthResp

func (p *UserServiceRegisterResult) GetSuccess() (v *AuthResp) {
	if !p.IsSetSuccess() {
		return UserServiceRegisterResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*AuthResp)
}

func (p *UserServiceRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceRegisterResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterResult(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterResult = map[int16]string{
	0: "success",
}

type UserServiceLoginArgs struct {
	Req *LoginReq `thrift:"req,1" frugal:"1,default,LoginReq" json:"req"`
}

func NewUserServiceLoginArgs() *UserServiceLoginArgs {
	return &UserServiceLoginArgs{}
}

func (p *UserServiceLoginArgs) InitDefault() {
}

var UserServiceLoginArgs_Req_DEFAULT *LoginReq

func (p *UserServiceLoginArgs) GetReq() (v *LoginReq) {
	if !p.IsSetReq() {
		return UserServiceLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceLoginArgs) SetReq(val *LoginReq) {
	p.Req = val
}

func (p *UserServiceLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginArgs(%+v)", *p)
}

var fieldIDToName_UserServiceLoginArgs = map[int16]string{
	1: "req",
}

type UserServiceLoginResult struct {
	Success *AuthResp `thrift:"success,0,optional" frugal:"0,optional,AuthResp" json:"success,omitempty"`
}

func NewUserServiceLoginResult() *UserServiceLoginResult {
	return &UserServiceLoginResult{}
}

func (p *UserServiceLoginResult) InitDefault() {
}

var UserServiceLoginResult_Success_DEFAULT *AuthResp

func (p *UserServiceLoginResult) GetSuccess() (v *AuthResp) {
	if !p.IsSetSuccess() {
		return UserServiceLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*AuthResp)
}

func (p *UserServiceLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginResult(%+v)", *p)
}

var fieldIDToName_UserServiceLoginResult = map[int16]string{
	0: "success",
}

type UserServiceSocialLoginArgs struct {
	Provider string `thrift:"provider,1" frugal:"1,default,string" json:"provider"`
}

func NewUserServiceSocialLoginArgs() *UserServiceSocialLoginArgs {
	return &UserServiceSocialLoginArgs{}
}

func (p *UserServiceSocialLoginArgs) InitDefault() {
}

func (p *UserServiceSocialLoginArgs) GetProvider() (v string) {
	return p.Provider
}
func (p *UserServiceSocialLoginArgs) SetProvider(val string) {
	p.Provider = val
}

func (p *UserServiceSocialLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceSocialLoginArgs(%+v)", *p)
}

var fieldIDToName_UserServiceSocialLoginArgs = map[int16]string{
	1: "provider",
}

type UserServiceSocialLoginResult struct {
	Success *AuthResp `thrift:"success,0,optional" frugal:"0,optional,AuthResp" json:"success,omitempty"`
}

func NewUserServiceSocialLoginResult() *UserServiceSocialLoginResult {
	return &UserServiceSocialLoginResult{}
}

func (p *UserServiceSocialLoginResult) InitDefault() {
}

var UserServiceSocialLoginResult_Success_DEFAULT *AuthResp

func (p *UserServiceSocialLoginResult) GetSuccess() (v *AuthResp) {
	if !p.IsSetSuccess() {
		return UserServiceSocialLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceSocialLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*AuthResp)
}

func (p *UserServiceSocialLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceSocialLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceSocialLoginResult(%+v)", *p)
}

var fieldIDToName_UserServiceSocialLoginResult = map[int16]string{
	0: "success",
}

type UserServiceResetPasswordArgs struct {
	Req *ResetPasswordReq `thrift:"req,1" frugal:"1,default,ResetPasswordReq" json:"req"`
}

func NewUserServiceResetPasswordArgs() *UserServiceResetPasswordArgs {
	return &UserServiceResetPasswordArgs{}
}

func (p *UserServiceResetPasswordArgs) InitDefault() {
}

var UserServiceResetPasswordArgs_Req_DEFAULT *ResetPasswordReq

func (p *UserServiceResetPasswordArgs) GetReq() (v *ResetPasswordReq) {
	if !p.IsSetReq() {
		return UserServiceResetPasswordArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceResetPasswordArgs) SetReq(val *ResetPasswordReq) {
	p.Req = val
}

func (p *UserServiceResetPasswordArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceResetPasswordArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceResetPasswordArgs(%+v)", *p)
}

var fieldIDToName_UserServiceResetPasswordArgs = map[int16]string{
	1: "req",
}

type UserServiceResetPasswordResult struct {
	Success *bool `thrift:"success,0,optional" frugal:"0,optional,bool" json:"success,omitempty"`
}

func NewUserServiceResetPasswordResult() *UserServiceResetPasswordResult {
	return &UserServiceResetPasswordResult{}
}

func (p *UserServiceResetPasswordResult) InitDefault() {
}

var UserServiceResetPasswordResult_Success_DEFAULT bool

func (p *UserServiceResetPasswordResult) GetSuccess() (v bool) {
	if !p.IsSetSuccess() {
		return UserServiceResetPasswordResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *UserServiceResetPasswordResult) SetSuccess(x interface{}) {
	p.Success = x.(*bool)
}

func (p *UserServiceResetPasswordResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceResetPasswordResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceResetPasswordResult(%+v)", *p)
}

var fieldIDToName_UserServiceResetPasswordResult = map[int16]string{
	0: "success",
}

type UserServiceGetUserByIDArgs struct {
	Id int64 `thrift:"id,1" frugal:"1,default,i64" json:"id"`
}

func NewUserServiceGetUserByIDArgs() *UserServiceGetUserByIDArgs {
	return &UserServiceGetUserByIDArgs{}
}

func (p *UserServiceGetUserByIDArgs) InitDefault() {
}

func (p *UserServiceGetUserByIDArgs) GetId() (v int64) {
	return p.Id
}
func (p *UserServiceGetUserByIDArgs) SetId(val int64) {
	p.Id = val
}

func (p *UserServiceGetUserByIDArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserByIDArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserByIDArgs = map[int16]string{
	1: "id",
}

type UserServiceGetUserByIDResult struct {
	Success *User `thrift:"success,0,optional" frugal:"0,optional,User" json:"success,omitempty"`
}

func NewUserServiceGetUserByIDResult() *UserServiceGetUserByIDResult {
	return &UserServiceGetUserByIDResult{}
}

func (p *UserServiceGetUserByIDResult) InitDefault() {
}

var UserServiceGetUserByIDResult_Success_DEFAULT *User

func (p *UserServiceGetUserByIDResult) GetSuccess() (v *User) {
	if !p.IsSetSuccess() {
		return UserServiceGetUserByIDResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetUserByIDResult) SetSuccess(x interface{}) {
	p.Success = x.(*User)
}

func (p *UserServiceGetUserByIDResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetUserByIDResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserByIDResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserByIDResult = map[int16]string{
	0: "success",
}

type UserServiceGetUsersByIDsArgs struct {
	Ids []int64 `thrift:"ids,1" frugal:"1,default,list<i64>" json:"ids"`
}

func NewUserServiceGetUsersByIDsArgs() *UserServiceGetUsersByIDsArgs {
	return &UserServiceGetUsersByIDsArgs{}
}

func (p *UserServiceGetUsersByIDsArgs) InitDefault() {
}

func (p *UserServiceGetUsersByIDsArgs) GetIds() (v []int64) {
	return p.Ids
}
func (p *UserServiceGetUsersByIDsArgs) SetIds(val []int64) {
	p.Ids = val
}

func (p *UserServiceGetUsersByIDsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUsersByIDsArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetUsersByIDsArgs = map[int16]string{
	1: "ids",
}

type UserServiceGetUsersByIDsResult struct {
	Success []*User `thrift:"success,0,optional" frugal:"0,optional,list<User>" json:"success,omitempty"`
}

func NewUserServiceGetUsersByIDsResult() *UserServiceGetUsersByIDsResult {
	return &UserServiceGetUsersByIDsResult{}
}

func (p *UserServiceGetUsersByIDsResult) InitDefault() {
}

var UserServiceGetUsersByIDsResult_Success_DEFAULT []*User

func (p *UserServiceGetUsersByIDsResult) GetSuccess() (v []*User) {
	if !p.IsSetSuccess() {
		return UserServiceGetUsersByIDsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetUsersByIDsResult) SetSuccess(x interface{}) {
	p.Success = x.([]*User)
}

func (p *UserServiceGetUsersByIDsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetUsersByIDsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUsersByIDsResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetUsersByIDsResult = map[int16]string{
	0: "success",
}

type UserServiceUpdateProfileArgs struct {
	Req *UpdateProfileReq `thrift:"req,1" frugal:"1,default,UpdateProfileReq" json:"req"`
}

func NewUserServiceUpdateProfileArgs() *UserServiceUpdateProfileArgs {
	return &UserServiceUpdateProfileArgs{}
}

func (p *UserServiceUpdateProfileArgs) InitDefault() {
}

var UserServiceUpdateProfileArgs_Req_DEFAULT *UpdateProfileReq

func (p *UserServiceUpdateProfileArgs) GetReq() (v *UpdateProfileReq) {
	if !p.IsSetReq() {
		return UserServiceUpdateProfileArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceUpdateProfileArgs) SetReq(val *UpdateProfileReq) {
	p.Req = val
}

func (p *UserServiceUpdateProfileArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceUpdateProfileArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateProfileArgs(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateProfileArgs = map[int16]string{
	1: "req",
}

type UserServiceUpdateProfileResult struct {
	Success *User `thrift:"success,0,optional" frugal:"0,optional,User" json:"success,omitempty"`
}

func NewUserServiceUpdateProfileResult() *UserServiceUpdateProfileResult {
	return &UserServiceUpdateProfileResult{}
}

func (p *UserServiceUpdateProfileResult) InitDefault() {
}

var UserServiceUpdateProfileResult_Success_DEFAULT *User

func (p *UserServiceUpdateProfileResult) GetSuccess() (v *User) {
	if !p.IsSetSuccess() {
		return UserServiceUpdateProfileResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceUpdateProfileResult) SetSuccess(x interface{}) {
	p.Success = x.(*User)
}

func (p *UserServiceUpdateProfileResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceUpdateProfileResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateProfileResult(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateProfileResult = map[int16]string{
	0: "success",
}

type UserServiceUpdatePasswordArgs struct {
	Req *UpdatePasswordReq `thrift:"req,1" frugal:"1,default,UpdatePasswordReq" json:"req"`
}

func NewUserServiceUpdatePasswordArgs() *UserServiceUpdatePasswordArgs {
	return &UserServiceUpdatePasswordArgs{}
}

func (p *UserServiceUpdatePasswordArgs) InitDefault() {
}

var UserServiceUpdatePasswordArgs_Req_DEFAULT *UpdatePasswordReq

func (p *UserServiceUpdatePasswordArgs) GetReq() (v *UpdatePasswordReq) {
	if !p.IsSetReq() {
		return UserServiceUpdatePasswordArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceUpdatePasswordArgs) SetReq(val *UpdatePasswordReq) {
	p.Req = val
}

func (p *UserServiceUpdatePasswordArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceUpdatePasswordArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdatePasswordArgs(%+v)", *p)
}

var fieldIDToName_UserServiceUpdatePasswordArgs = map[int16]string{
	1: "req",
}

type UserServiceUpdatePasswordResult struct {
	Success *bool `thrift:"success,0,optional" frugal:"0,optional,bool" json:"success,omitempty"`
}

func NewUserServiceUpdatePasswordResult() *UserServiceUpdatePasswordResult {
	return &UserServiceUpdatePasswordResult{}
}

func (p *UserServiceUpdatePasswordResult) InitDefault() {
}

var UserServiceUpdatePasswordResult_Success_DEFAULT bool

func (p *UserServiceUpdatePasswordResult) GetSuccess() (v bool) {
	if !p.IsSetSuccess() {
		return UserServiceUpdatePasswordResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *UserServiceUpdatePasswordResult) SetSuccess(x interface{}) {
	p.Success = x.(*bool)
}

func (p *UserServiceUpdatePasswordResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceUpdatePasswordResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdatePasswordResult(%+v)", *p)
}

var fieldIDToName_UserServiceUpdatePasswordResult = map[int16]string{
	0: "success",
}

type UserServiceGetNotificationsArgs struct {
	Req *GetListReq `thrift:"req,1" frugal:"1,default,GetListReq" json:"req"`
}

func NewUserServiceGetNotificationsArgs() *UserServiceGetNotificationsArgs {
	return &UserServiceGetNotificationsArgs{}
}

func (p *UserServiceGetNotificationsArgs) InitDefault() {
}

var UserServiceGetNotificationsArgs_Req_DEFAULT *GetListReq

func (p *UserServiceGetNotificationsArgs) GetReq() (v *GetListReq) {
	if !p.IsSetReq() {
		return UserServiceGetNotificationsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceGetNotificationsArgs) SetReq(val *GetListReq) {
	p.Req = val
}

func (p *UserServiceGetNotificationsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceGetNotificationsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetNotificationsArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetNotificationsArgs = map[int16]string{
	1: "req",
}

type UserServiceGetNotificationsResult struct {
	Success *PaginatedResp `thrift:"success,0,optional" frugal:"0,optional,PaginatedResp" json:"success,omitempty"`
}

func NewUserServiceGetNotificationsResult() *UserServiceGetNotificationsResult {
	return &UserServiceGetNotificationsResult{}
}

func (p *UserServiceGetNotificationsResult) InitDefault() {
}

var UserServiceGetNotificationsResult_Success_DEFAULT *PaginatedResp

func (p *UserServiceGetNotificationsResult) GetSuccess() (v *PaginatedResp) {
	if !p.IsSetSuccess() {
		return UserServiceGetNotificationsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetNotificationsResult) SetSuccess(x interface{}) {
	p.Success = x.(*PaginatedResp)
}

func (p *UserServiceGetNotificationsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetNotificationsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetNotificationsResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetNotificationsResult = map[int16]string{
	0: "success",
}

type UserServiceReadNotificationArgs struct {
	UserId  int64 `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	NotifId int64 `thrift:"notifId,2" frugal:"2,default,i64" json:"notifId"`
}

func NewUserServiceReadNotificationArgs() *UserServiceReadNotificationArgs {
	return &UserServiceReadNotificationArgs{}
}

func (p *UserServiceReadNotificationArgs) InitDefault() {
}

func (p *UserServiceReadNotificationArgs) GetUserId() (v int64) {
	return p.UserId
}

func (p *UserServiceReadNotificationArgs) GetNotifId() (v int64) {
	return p.NotifId
}
func (p *UserServiceReadNotificationArgs) SetUserId(val int64) {
	p.UserId = val
}
func (p *UserServiceReadNotificationArgs) SetNotifId(val int64) {
	p.NotifId = val
}

func (p *UserServiceReadNotificationArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceReadNotificationArgs(%+v)", *p)
}

var fieldIDToName_UserServiceReadNotificationArgs = map[int16]string{
	1: "userId",
	2: "notifId",
}

type UserServiceReadNotificationResult struct {
	Success *bool `thrift:"success,0,optional" frugal:"0,optional,bool" json:"success,omitempty"`
}

func NewUserServiceReadNotificationResult() *UserServiceReadNotificationResult {
	return &UserServiceReadNotificationResult{}
}

func (p *UserServiceReadNotificationResult) InitDefault() {
}

var UserServiceReadNotificationResult_Success_DEFAULT bool

func (p *UserServiceReadNotificationResult) GetSuccess() (v bool) {
	if !p.IsSetSuccess() {
		return UserServiceReadNotificationResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *UserServiceReadNotificationResult) SetSuccess(x interface{}) {
	p.Success = x.(*bool)
}

func (p *UserServiceReadNotificationResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceReadNotificationResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceReadNotificationResult(%+v)", *p)
}

var fieldIDToName_UserServiceReadNotificationResult = map[int16]string{
	0: "success",
}

type UserServiceCreateNotificationArgs struct {
	Req *CreateNotificationReq `thrift:"req,1" frugal:"1,default,CreateNotificationReq" json:"req"`
}

func NewUserServiceCreateNotificationArgs() *UserServiceCreateNotificationArgs {
	return &UserServiceCreateNotificationArgs{}
}

func (p *UserServiceCreateNotificationArgs) InitDefault() {
}

var UserServiceCreateNotificationArgs_Req_DEFAULT *CreateNotificationReq

func (p *UserServiceCreateNotificationArgs) GetReq() (v *CreateNotificationReq) {
	if !p.IsSetReq() {
		return UserServiceCreateNotificationArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceCreateNotificationArgs) SetReq(val *CreateNotificationReq) {
	p.Req = val
}

func (p *UserServiceCreateNotificationArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceCreateNotificationArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCreateNotificationArgs(%+v)", *p)
}

var fieldIDToName_UserServiceCreateNotificationArgs = map[int16]string{
	1: "req",
}

type UserServiceCreateNotificationResult struct {
	Success *bool `thrift:"success,0,optional" frugal:"0,optional,bool" json:"success,omitempty"`
}

func NewUserServiceCreateNotificationResult() *UserServiceCreateNotificationResult {
	return &UserServiceCreateNotificationResult{}
}

func (p *UserServiceCreateNotificationResult) InitDefault() {
}

var UserServiceCreateNotificationResult_Success_DEFAULT bool

func (p *UserServiceCreateNotificationResult) GetSuccess() (v bool) {
	if !p.IsSetSuccess() {
		return UserServiceCreateNotificationResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *UserServiceCreateNotificationResult) SetSuccess(x interface{}) {
	p.Success = x.(*bool)
}

func (p *UserServiceCreateNotificationResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceCreateNotificationResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCreateNotificationResult(%+v)", *p)
}

var fieldIDToName_UserServiceCreateNotificationResult = map[int16]string{
	0: "success",
}

type UserServiceGetInteractionsArgs struct {
	Req *GetListReq `thrift:"req,1" frugal:"1,default,GetListReq" json:"req"`
}

func NewUserServiceGetInteractionsArgs() *UserServiceGetInteractionsArgs {
	return &UserServiceGetInteractionsArgs{}
}

func (p *UserServiceGetInteractionsArgs) InitDefault() {
}

var UserServiceGetInteractionsArgs_Req_DEFAULT *GetListReq

func (p *UserServiceGetInteractionsArgs) GetReq() (v *GetListReq) {
	if !p.IsSetReq() {
		return UserServiceGetInteractionsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceGetInteractionsArgs) SetReq(val *GetListReq) {
	p.Req = val
}

func (p *UserServiceGetInteractionsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceGetInteractionsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetInteractionsArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetInteractionsArgs = map[int16]string{
	1: "req",
}

type UserServiceGetInteractionsResult struct {
	Success *PaginatedResp `thrift:"success,0,optional" frugal:"0,optional,PaginatedResp" json:"success,omitempty"`
}

func NewUserServiceGetInteractionsResult() *UserServiceGetInteractionsResult {
	return &UserServiceGetInteractionsResult{}
}

func (p *UserServiceGetInteractionsResult) InitDefault() {
}

var UserServiceGetInteractionsResult_Success_DEFAULT *PaginatedResp

func (p *UserServiceGetInteractionsResult) GetSuccess() (v *PaginatedResp) {
	if !p.IsSetSuccess() {
		return UserServiceGetInteractionsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetInteractionsResult) SetSuccess(x interface{}) {
	p.Success = x.(*PaginatedResp)
}

func (p *UserServiceGetInteractionsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetInteractionsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetInteractionsResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetInteractionsResult = map[int16]string{
	0: "success",
}

type UserServiceCreateInteractionArgs struct {
	Req *CreateInteractionReq `thrift:"req,1" frugal:"1,default,CreateInteractionReq" json:"req"`
}

func NewUserServiceCreateInteractionArgs() *UserServiceCreateInteractionArgs {
	return &UserServiceCreateInteractionArgs{}
}

func (p *UserServiceCreateInteractionArgs) InitDefault() {
}

var UserServiceCreateInteractionArgs_Req_DEFAULT *CreateInteractionReq

func (p *UserServiceCreateInteractionArgs) GetReq() (v *CreateInteractionReq) {
	if !p.IsSetReq() {
		return UserServiceCreateInteractionArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceCreateInteractionArgs) SetReq(val *CreateInteractionReq) {
	p.Req = val
}

func (p *UserServiceCreateInteractionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceCreateInteractionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCreateInteractionArgs(%+v)", *p)
}

var fieldIDToName_UserServiceCreateInteractionArgs = map[int16]string{
	1: "req",
}

type UserServiceCreateInteractionResult struct {
	Success *bool `thrift:"success,0,optional" frugal:"0,optional,bool" json:"success,omitempty"`
}

func NewUserServiceCreateInteractionResult() *UserServiceCreateInteractionResult {
	return &UserServiceCreateInteractionResult{}
}

func (p *UserServiceCreateInteractionResult) InitDefault() {
}

var UserServiceCreateInteractionResult_Success_DEFAULT bool

func (p *UserServiceCreateInteractionResult) GetSuccess() (v bool) {
	if !p.IsSetSuccess() {
		return UserServiceCreateInteractionResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *UserServiceCreateInteractionResult) SetSuccess(x interface{}) {
	p.Success = x.(*bool)
}

func (p *UserServiceCreateInteractionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceCreateInteractionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCreateInteractionResult(%+v)", *p)
}

var fieldIDToName_UserServiceCreateInteractionResult = map[int16]string{
	0: "success",
}

type UserServiceAdminListUsersArgs struct {
	Req *AdminListUsersReq `thrift:"req,1" frugal:"1,default,AdminListUsersReq" json:"req"`
}

func NewUserServiceAdminListUsersArgs() *UserServiceAdminListUsersArgs {
	return &UserServiceAdminListUsersArgs{}
}

func (p *UserServiceAdminListUsersArgs) InitDefault() {
}

var UserServiceAdminListUsersArgs_Req_DEFAULT *AdminListUsersReq

func (p *UserServiceAdminListUsersArgs) GetReq() (v *AdminListUsersReq) {
	if !p.IsSetReq() {
		return UserServiceAdminListUsersArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceAdminListUsersArgs) SetReq(val *AdminListUsersReq) {
	p.Req = val
}

func (p *UserServiceAdminListUsersArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceAdminListUsersArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceAdminListUsersArgs(%+v)", *p)
}

var fieldIDToName_UserServiceAdminListUsersArgs = map[int16]string{
	1: "req",
}

type UserServiceAdminListUsersResult struct {
	Success *PaginatedResp `thrift:"success,0,optional" frugal:"0,optional,PaginatedResp" json:"success,omitempty"`
}

func NewUserServiceAdminListUsersResult() *UserServiceAdminListUsersResult {
	return &UserServiceAdminListUsersResult{}
}

func (p *UserServiceAdminListUsersResult) InitDefault() {
}

var UserServiceAdminListUsersResult_Success_DEFAULT *PaginatedResp

func (p *UserServiceAdminListUsersResult) GetSuccess() (v *PaginatedResp) {
	if !p.IsSetSuccess() {
		return UserServiceAdminListUsersResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceAdminListUsersResult) SetSuccess(x interface{}) {
	p.Success = x.(*PaginatedResp)
}

func (p *UserServiceAdminListUsersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceAdminListUsersResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceAdminListUsersResult(%+v)", *p)
}

var fieldIDToName_UserServiceAdminListUsersResult = map[int16]string{
	0: "success",
}

type UserServiceAdminGetUserArgs struct {
	Id int64 `thrift:"id,1" frugal:"1,default,i64" json:"id"`
}

func NewUserServiceAdminGetUserArgs() *UserServiceAdminGetUserArgs {
	return &UserServiceAdminGetUserArgs{}
}

func (p *UserServiceAdminGetUserArgs) InitDefault() {
}

func (p *UserServiceAdminGetUserArgs) GetId() (v int64) {
	return p.Id
}
func (p *UserServiceAdminGetUserArgs) SetId(val int64) {
	p.Id = val
}

func (p *UserServiceAdminGetUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceAdminGetUserArgs(%+v)", *p)
}

var fieldIDToName_UserServiceAdminGetUserArgs = map[int16]string{
	1: "id",
}

type UserServiceAdminGetUserResult struct {
	Success *User `thrift:"success,0,optional" frugal:"0,optional,User" json:"success,omitempty"`
}

func NewUserServiceAdminGetUserResult() *UserServiceAdminGetUserResult {
	return &UserServiceAdminGetUserResult{}
}

func (p *UserServiceAdminGetUserResult) InitDefault() {
}

var UserServiceAdminGetUserResult_Success_DEFAULT *User

func (p *UserServiceAdminGetUserResult) GetSuccess() (v *User) {
	if !p.IsSetSuccess() {
		return UserServiceAdminGetUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceAdminGetUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*User)
}

func (p *UserServiceAdminGetUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceAdminGetUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceAdminGetUserResult(%+v)", *p)
}

var fieldIDToName_UserServiceAdminGetUserResult = map[int16]string{
	0: "success",
}

type UserServiceAdminUpdateUserArgs struct {
	Req *AdminUpdateUserReq `thrift:"req,1" frugal:"1,default,AdminUpdateUserReq" json:"req"`
}

func NewUserServiceAdminUpdateUserArgs() *UserServiceAdminUpdateUserArgs {
	return &UserServiceAdminUpdateUserArgs{}
}

func (p *UserServiceAdminUpdateUserArgs) InitDefault() {
}

var UserServiceAdminUpdateUserArgs_Req_DEFAULT *AdminUpdateUserReq

func (p *UserServiceAdminUpdateUserArgs) GetReq() (v *AdminUpdateUserReq) {
	if !p.IsSetReq() {
		return UserServiceAdminUpdateUserArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceAdminUpdateUserArgs) SetReq(val *AdminUpdateUserReq) {
	p.Req = val
}

func (p *UserServiceAdminUpdateUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceAdminUpdateUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceAdminUpdateUserArgs(%+v)", *p)
}

var fieldIDToName_UserServiceAdminUpdateUserArgs = map[int16]string{
	1: "req",
}

type UserServiceAdminUpdateUserResult struct {
	Success *User `thrift:"success,0,optional" frugal:"0,optional,User" json:"success,omitempty"`
}

func NewUserServiceAdminUpdateUserResult() *UserServiceAdminUpdateUserResult {
	return &UserServiceAdminUpdateUserResult{}
}

func (p *UserServiceAdminUpdateUserResult) InitDefault() {
}

var UserServiceAdminUpdateUserResult_Success_DEFAULT *User

func (p *UserServiceAdminUpdateUserResult) GetSuccess() (v *User) {
	if !p.IsSetSuccess() {
		return UserServiceAdminUpdateUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceAdminUpdateUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*User)
}

func (p *UserServiceAdminUpdateUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceAdminUpdateUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceAdminUpdateUserResult(%+v)", *p)
}

var fieldIDToName_UserServiceAdminUpdateUserResult = map[int16]string{
	0: "success",
}

type UserServiceAdminDeleteUserArgs struct {
	Id int64 `thrift:"id,1" frugal:"1,default,i64" json:"id"`
}

func NewUserServiceAdminDeleteUserArgs() *UserServiceAdminDeleteUserArgs {
	return &UserServiceAdminDeleteUserArgs{}
}

func (p *UserServiceAdminDeleteUserArgs) InitDefault() {
}

func (p *UserServiceAdminDeleteUserArgs) GetId() (v int64) {
	return p.Id
}
func (p *UserServiceAdminDeleteUserArgs) SetId(val int64) {
	p.Id = val
}

func (p *UserServiceAdminDeleteUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceAdminDeleteUserArgs(%+v)", *p)
}

var fieldIDToName_UserServiceAdminDeleteUserArgs = map[int16]string{
	1: "id",
}

type UserServiceAdminDeleteUserResult struct {
	Success *bool `thrift:"success,0,optional" frugal:"0,optional,bool" json:"success,omitempty"`
}

func NewUserServiceAdminDeleteUserResult() *UserServiceAdminDeleteUserResult {
	return &UserServiceAdminDeleteUserResult{}
}

func (p *UserServiceAdminDeleteUserResult) InitDefault() {
}

var UserServiceAdminDeleteUserResult_Success_DEFAULT bool

func (p *UserServiceAdminDeleteUserResult) GetSuccess() (v bool) {
	if !p.IsSetSuccess() {
		return UserServiceAdminDeleteUserResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *UserServiceAdminDeleteUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*bool)
}

func (p *UserServiceAdminDeleteUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceAdminDeleteUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceAdminDeleteUserResult(%+v)", *p)
}

var fieldIDToName_UserServiceAdminDeleteUserResult = map[int16]string{
	0: "success",
}

type UserServiceAdminBroadcastArgs struct {
	Req *BroadcastReq `thrift:"req,1" frugal:"1,default,BroadcastReq" json:"req"`
}

func NewUserServiceAdminBroadcastArgs() *UserServiceAdminBroadcastArgs {
	return &UserServiceAdminBroadcastArgs{}
}

func (p *UserServiceAdminBroadcastArgs) InitDefault() {
}

var UserServiceAdminBroadcastArgs_Req_DEFAULT *BroadcastReq

func (p *UserServiceAdminBroadcastArgs) GetReq() (v *BroadcastReq) {
	if !p.IsSetReq() {
		return UserServiceAdminBroadcastArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceAdminBroadcastArgs) SetReq(val *BroadcastReq) {
	p.Req = val
}

func (p *UserServiceAdminBroadcastArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceAdminBroadcastArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceAdminBroadcastArgs(%+v)", *p)
}

var fieldIDToName_UserServiceAdminBroadcastArgs = map[int16]string{
	1: "req",
}

type UserServiceAdminBroadcastResult struct {
	Success *int32 `thrift:"success,0,optional" frugal:"0,optional,i32" json:"success,omitempty"`
}

func NewUserServiceAdminBroadcastResult() *UserServiceAdminBroadcastResult {
	return &UserServiceAdminBroadcastResult{}
}

func (p *UserServiceAdminBroadcastResult) InitDefault() {
}

var UserServiceAdminBroadcastResult_Success_DEFAULT int32

func (p *UserServiceAdminBroadcastResult) GetSuccess() (v int32) {
	if !p.IsSetSuccess() {
		return UserServiceAdminBroadcastResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *UserServiceAdminBroadcastResult) SetSuccess(x interface{}) {
	p.Success = x.(*int32)
}

func (p *UserServiceAdminBroadcastResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceAdminBroadcastResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceAdminBroadcastResult(%+v)", *p)
}

var fieldIDToName_UserServiceAdminBroadcastResult = map[int16]string{
	0: "success",
}

type UserServiceCountAllArgs struct {
}

func NewUserServiceCountAllArgs() *UserServiceCountAllArgs {
	return &UserServiceCountAllArgs{}
}

func (p *UserServiceCountAllArgs) InitDefault() {
}

func (p *UserServiceCountAllArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCountAllArgs(%+v)", *p)
}

var fieldIDToName_UserServiceCountAllArgs = map[int16]string{}

type UserServiceCountAllResult struct {
	Success *int64 `thrift:"success,0,optional" frugal:"0,optional,i64" json:"success,omitempty"`
}

func NewUserServiceCountAllResult() *UserServiceCountAllResult {
	return &UserServiceCountAllResult{}
}

func (p *UserServiceCountAllResult) InitDefault() {
}

var UserServiceCountAllResult_Success_DEFAULT int64

func (p *UserServiceCountAllResult) GetSuccess() (v int64) {
	if !p.IsSetSuccess() {
		return UserServiceCountAllResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *UserServiceCountAllResult) SetSuccess(x interface{}) {
	p.Success = x.(*int64)
}

func (p *UserServiceCountAllResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceCountAllResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCountAllResult(%+v)", *p)
}

var fieldIDToName_UserServiceCountAllResult = map[int16]string{
	0: "success",
}
