// Code generated by Kitex v0.16.3. DO NOT EDIT.

package userservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	user "parrot-backend-go/kitex_gen/user"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	SendCode(ctx context.Context, email string, callOptions ...callopt.Option) (r *user.SendCodeResp, err error)
	Register(ctx context.Context, req *user.RegisterReq, callOptions ...callopt.Option) (r *user.AuthResp, err error)
	Login(ctx context.Context, req *user.LoginReq, callOptions ...callopt.Option) (r *user.AuthResp, err error)
	SocialLogin(ctx context.Context, provider string, callOptions ...callopt.Option) (r *user.AuthResp, err error)
	ResetPassword(ctx context.Context, req *user.ResetPasswordReq, callOptions ...callopt.Option) (r bool, err error)
	GetUserByID(ctx context.Context, id int64, callOptions ...callopt.Option) (r *user.User, err error)
	GetUsersByIDs(ctx context.Context, ids []int64, callOptions ...callopt.Option) (r []*user.User, err error)
	UpdateProfile(ctx context.Context, req *user.UpdateProfileReq, callOptions ...callopt.Option) (r *user.User, err error)
	UpdatePassword(ctx context.Context, req *user.UpdatePasswordReq, callOptions ...callopt.Option) (r bool, err error)
	GetNotifications(ctx context.Context, req *user.GetListReq, callOptions ...callopt.Option) (r *user.PaginatedResp, err error)
	ReadNotification(ctx context.Context, userId int64, notifId int64, callOptions ...callopt.Option) (r bool, err error)
	CreateNotification(ctx context.Context, req *user.CreateNotificationReq, callOptions ...callopt.Option) (r bool, err error)
	GetInteractions(ctx context.Context, req *user.GetListReq, callOptions ...callopt.Option) (r *user.PaginatedResp, err error)
	CreateInteraction(ctx context.Context, req *user.CreateInteractionReq, callOptions ...callopt.Option) (r bool, err error)
	AdminListUsers(ctx context.Context, req *user.AdminListUsersReq, callOptions ...callopt.Option) (r *user.PaginatedResp, err error)
	AdminGetUser(ctx context.Context, id int64, callOptions ...callopt.Option) (r *user.User, err error)
	AdminUpdateUser(ctx context.Context, req *user.AdminUpdateUserReq, callOptions ...callopt.Option) (r *user.User, err error)
	AdminDeleteUser(ctx context.Context, id int64, callOptions ...callopt.Option) (r bool, err error)
	AdminBroadcast(ctx context.Context, req *user.BroadcastReq, callOptions ...callopt.Option) (r int32, err error)
	CountAll(ctx context.Context, callOptions ...callopt.Option) (r int64, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) SendCode(ctx context.Context, email string, callOptions ...callopt.Option) (r *user.SendCodeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendCode(ctx, email)
}

func (p *kUserServiceClient) Register(ctx context.Context, req *user.RegisterReq, callOptions ...callopt.Option) (r *user.AuthResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, req)
}

func (p *kUserServiceClient) Login(ctx context.Context, req *user.LoginReq, callOptions ...callopt.Option) (r *user.AuthResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, req)
}

func (p *kUserServiceClient) SocialLogin(ctx context.Context, provider string, callOptions ...callopt.Option) (r *user.AuthResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SocialLogin(ctx, provider)
}

func (p *kUserServiceClient) ResetPassword(ctx context.Context, req *user.ResetPasswordReq, callOptions ...callopt.Option) (r bool, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ResetPassword(ctx, req)
}

func (p *kUserServiceClient) GetUserByID(ctx context.Context, id int64, callOptions ...callopt.Option) (r *user.User, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserByID(ctx, id)
}

func (p *kUserServiceClient) GetUsersByIDs(ctx context.Context, ids []int64, callOptions ...callopt.Option) (r []*user.User, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUsersByIDs(ctx, ids)
}

func (p *kUserServiceClient) UpdateProfile(ctx context.Context, req *user.UpdateProfileReq, callOptions ...callopt.Option) (r *user.User, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateProfile(ctx, req)
}

func (p *kUserServiceClient) UpdatePassword(ctx context.Context, req *user.UpdatePasswordReq, callOptions ...callopt.Option) (r bool, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdatePassword(ctx, req)
}

func (p *kUserServiceClient) GetNotifications(ctx context.Context, req *user.GetListReq, callOptions ...callopt.Option) (r *user.PaginatedResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetNotifications(ctx, req)
}

func (p *kUserServiceClient) ReadNotification(ctx context.Context, userId int64, notifId int64, callOptions ...callopt.Option) (r bool, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReadNotification(ctx, userId, notifId)
}

func (p *kUserServiceClient) CreateNotification(ctx context.Context, req *user.CreateNotificationReq, callOptions ...callopt.Option) (r bool, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateNotification(ctx, req)
}

func (p *kUserServiceClient) GetInteractions(ctx context.Context, req *user.GetListReq, callOptions ...callopt.Option) (r *user.PaginatedResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetInteractions(ctx, req)
}

func (p *kUserServiceClient) CreateInteraction(ctx context.Context, req *user.CreateInteractionReq, callOptions ...callopt.Option) (r bool, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateInteraction(ctx, req)
}

func (p *kUserServiceClient) AdminListUsers(ctx context.Context, req *user.AdminListUsersReq, callOptions ...callopt.Option) (r *user.PaginatedResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AdminListUsers(ctx, req)
}

func (p *kUserServiceClient) AdminGetUser(ctx context.Context, id int64, callOptions ...callopt.Option) (r *user.User, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AdminGetUser(ctx, id)
}

func (p *kUserServiceClient) AdminUpdateUser(ctx context.Context, req *user.AdminUpdateUserReq, callOptions ...callopt.Option) (r *user.User, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AdminUpdateUser(ctx, req)
}

func (p *kUserServiceClient) AdminDeleteUser(ctx context.Context, id int64, callOptions ...callopt.Option) (r bool, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AdminDeleteUser(ctx, id)
}

func (p *kUserServiceClient) AdminBroadcast(ctx context.Context, req *user.BroadcastReq, callOptions ...callopt.Option) (r int32, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AdminBroadcast(ctx, req)
}

func (p *kUserServiceClient) CountAll(ctx context.Context, callOptions ...callopt.Option) (r int64, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CountAll(ctx)
}
