// Code generated by Kitex v0.16.3. DO NOT EDIT.

package userservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	user "parrot-backend-go/kitex_gen/user"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"SendCode": kitex.NewMethodInfo(
		sendCodeHandler,
		newUserServiceSendCodeArgs,
		newUserServiceSendCodeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Register": kitex.NewMethodInfo(
		registerHandler,
		newUserServiceRegisterArgs,
		newUserServiceRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newUserServiceLoginArgs,
		newUserServiceLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SocialLogin": kitex.NewMethodInfo(
		socialLoginHandler,
		newUserServiceSocialLoginArgs,
		newUserServiceSocialLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ResetPassword": kitex.NewMethodInfo(
		resetPasswordHandler,
		newUserServiceResetPasswordArgs,
		newUserServiceResetPasswordResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUserByID": kitex.NewMethodInfo(
		getUserByIDHandler,
		newUserServiceGetUserByIDArgs,
		newUserServiceGetUserByIDResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUsersByIDs": kitex.NewMethodInfo(
		getUsersByIDsHandler,
		newUserServiceGetUsersByIDsArgs,
		newUserServiceGetUsersByIDsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateProfile": kitex.NewMethodInfo(
		updateProfileHandler,
		newUserServiceUpdateProfileArgs,
		newUserServiceUpdateProfileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdatePassword": kitex.NewMethodInfo(
		updatePasswordHandler,
		newUserServiceUpdatePasswordArgs,
		newUserServiceUpdatePasswordResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetNotifications": kitex.NewMethodInfo(
		getNotificationsHandler,
		newUserServiceGetNotificationsArgs,
		newUserServiceGetNotificationsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ReadNotification": kitex.NewMethodInfo(
		readNotificationHandler,
		newUserServiceReadNotificationArgs,
		newUserServiceReadNotificationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateNotification": kitex.NewMethodInfo(
		createNotificationHandler,
		newUserServiceCreateNotificationArgs,
		newUserServiceCreateNotificationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetInteractions": kitex.NewMethodInfo(
		getInteractionsHandler,
		newUserServiceGetInteractionsArgs,
		newUserServiceGetInteractionsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateInteraction": kitex.NewMethodInfo(
		createInteractionHandler,
		newUserServiceCreateInteractionArgs,
		newUserServiceCreateInteractionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AdminListUsers": kitex.NewMethodInfo(
		adminListUsersHandler,
		newUserServiceAdminListUsersArgs,
		newUserServiceAdminListUsersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AdminGetUser": kitex.NewMethodInfo(
		adminGetUserHandler,
		newUserServiceAdminGetUserArgs,
		newUserServiceAdminGetUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AdminUpdateUser": kitex.NewMethodInfo(
		adminUpdateUserHandler,
		newUserServiceAdminUpdateUserArgs,
		newUserServiceAdminUpdateUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AdminDeleteUser": kitex.NewMethodInfo(
		adminDeleteUserHandler,
		newUserServiceAdminDeleteUserArgs,
		newUserServiceAdminDeleteUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AdminBroadcast": kitex.NewMethodInfo(
		adminBroadcastHandler,
		newUserServiceAdminBroadcastArgs,
		newUserServiceAdminBroadcastResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CountAll": kitex.NewMethodInfo(
		countAllHandler,
		newUserServiceCountAllArgs,
		newUserServiceCountAllResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	userServiceServiceInfo                = NewServiceInfo()
	userServiceServiceInfoForClient       = NewServiceInfoForClient()
	userServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*user.UserService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "user",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func sendCodeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceSendCodeArgs)
	realResult := result.(*user.UserServiceSendCodeResult)
	success, err := handler.(user.UserService).SendCode(ctx, realArg.Email)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceSendCodeArgs() interface{} {
	return user.NewUserServiceSendCodeArgs()
}

func newUserServiceSendCodeResult() interface{} {
	return user.NewUserServiceSendCodeResult()
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceRegisterArgs)
	realResult := result.(*user.UserServiceRegisterResult)
	success, err := handler.(user.UserService).Register(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceRegisterArgs() interface{} {
	return user.NewUserServiceRegisterArgs()
}

func newUserServiceRegisterResult() interface{} {
	return user.NewUserServiceRegisterResult()
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceLoginArgs)
	realResult := result.(*user.UserServiceLoginResult)
	success, err := handler.(user.UserService).Login(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceLoginArgs() interface{} {
	return user.NewUserServiceLoginArgs()
}

func newUserServiceLoginResult() interface{} {
	return user.NewUserServiceLoginResult()
}

func socialLoginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceSocialLoginArgs)
	realResult := result.(*user.UserServiceSocialLoginResult)
	success, err := handler.(user.UserService).SocialLogin(ctx, realArg.Provider)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceSocialLoginArgs() interface{} {
	return user.NewUserServiceSocialLoginArgs()
}

func newUserServiceSocialLoginResult() interface{} {
	return user.NewUserServiceSocialLoginResult()
}

func resetPasswordHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceResetPasswordArgs)
	realResult := result.(*user.UserServiceResetPasswordResult)
	success, err := handler.(user.UserService).ResetPassword(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newUserServiceResetPasswordArgs() interface{} {
	return user.NewUserServiceResetPasswordArgs()
}

func newUserServiceResetPasswordResult() interface{} {
	return user.NewUserServiceResetPasswordResult()
}

func getUserByIDHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceGetUserByIDArgs)
	realResult := result.(*user.UserServiceGetUserByIDResult)
	success, err := handler.(user.UserService).GetUserByID(ctx, realArg.Id)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetUserByIDArgs() interface{} {
	return user.NewUserServiceGetUserByIDArgs()
}

func newUserServiceGetUserByIDResult() interface{} {
	return user.NewUserServiceGetUserByIDResult()
}

func getUsersByIDsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceGetUsersByIDsArgs)
	realResult := result.(*user.UserServiceGetUsersByIDsResult)
	success, err := handler.(user.UserService).GetUsersByIDs(ctx, realArg.Ids)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetUsersByIDsArgs() interface{} {
	return user.NewUserServiceGetUsersByIDsArgs()
}

func newUserServiceGetUsersByIDsResult() interface{} {
	return user.NewUserServiceGetUsersByIDsResult()
}

func updateProfileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceUpdateProfileArgs)
	realResult := result.(*user.UserServiceUpdateProfileResult)
	success, err := handler.(user.UserService).UpdateProfile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceUpdateProfileArgs() interface{} {
	return user.NewUserServiceUpdateProfileArgs()
}

func newUserServiceUpdateProfileResult() interface{} {
	return user.NewUserServiceUpdateProfileResult()
}

func updatePasswordHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceUpdatePasswordArgs)
	realResult := result.(*user.UserServiceUpdatePasswordResult)
	success, err := handler.(user.UserService).UpdatePassword(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newUserServiceUpdatePasswordArgs() interface{} {
	return user.NewUserServiceUpdatePasswordArgs()
}

func newUserServiceUpdatePasswordResult() interface{} {
	return user.NewUserServiceUpdatePasswordResult()
}

func getNotificationsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceGetNotificationsArgs)
	realResult := result.(*user.UserServiceGetNotificationsResult)
	success, err := handler.(user.UserService).GetNotifications(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetNotificationsArgs() interface{} {
	return user.NewUserServiceGetNotificationsArgs()
}

func newUserServiceGetNotificationsResult() interface{} {
	return user.NewUserServiceGetNotificationsResult()
}

func readNotificationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceReadNotificationArgs)
	realResult := result.(*user.UserServiceReadNotificationResult)
	success, err := handler.(user.UserService).ReadNotification(ctx, realArg.UserId, realArg.NotifId)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newUserServiceReadNotificationArgs() interface{} {
	return user.NewUserServiceReadNotificationArgs()
}

func newUserServiceReadNotificationResult() interface{} {
	return user.NewUserServiceReadNotificationResult()
}

func createNotificationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceCreateNotificationArgs)
	realResult := result.(*user.UserServiceCreateNotificationResult)
	success, err := handler.(user.UserService).CreateNotification(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newUserServiceCreateNotificationArgs() interface{} {
	return user.NewUserServiceCreateNotificationArgs()
}

func newUserServiceCreateNotificationResult() interface{} {
	return user.NewUserServiceCreateNotificationResult()
}

func getInteractionsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceGetInteractionsArgs)
	realResult := result.(*user.UserServiceGetInteractionsResult)
	success, err := handler.(user.UserService).GetInteractions(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetInteractionsArgs() interface{} {
	return user.NewUserServiceGetInteractionsArgs()
}

func newUserServiceGetInteractionsResult() interface{} {
	return user.NewUserServiceGetInteractionsResult()
}

func createInteractionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceCreateInteractionArgs)
	realResult := result.(*user.UserServiceCreateInteractionResult)
	success, err := handler.(user.UserService).CreateInteraction(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newUserServiceCreateInteractionArgs() interface{} {
	return user.NewUserServiceCreateInteractionArgs()
}

func newUserServiceCreateInteractionResult() interface{} {
	return user.NewUserServiceCreateInteractionResult()
}

func adminListUsersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceAdminListUsersArgs)
	realResult := result.(*user.UserServiceAdminListUsersResult)
	success, err := handler.(user.UserService).AdminListUsers(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceAdminListUsersArgs() interface{} {
	return user.NewUserServiceAdminListUsersArgs()
}

func newUserServiceAdminListUsersResult() interface{} {
	return user.NewUserServiceAdminListUsersResult()
}

func adminGetUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceAdminGetUserArgs)
	realResult := result.(*user.UserServiceAdminGetUserResult)
	success, err := handler.(user.UserService).AdminGetUser(ctx, realArg.Id)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceAdminGetUserArgs() interface{} {
	return user.NewUserServiceAdminGetUserArgs()
}

func newUserServiceAdminGetUserResult() interface{} {
	return user.NewUserServiceAdminGetUserResult()
}

func adminUpdateUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceAdminUpdateUserArgs)
	realResult := result.(*user.UserServiceAdminUpdateUserResult)
	success, err := handler.(user.UserService).AdminUpdateUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceAdminUpdateUserArgs() interface{} {
	return user.NewUserServiceAdminUpdateUserArgs()
}

func newUserServiceAdminUpdateUserResult() interface{} {
	return user.NewUserServiceAdminUpdateUserResult()
}

func adminDeleteUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceAdminDeleteUserArgs)
	realResult := result.(*user.UserServiceAdminDeleteUserResult)
	success, err := handler.(user.UserService).AdminDeleteUser(ctx, realArg.Id)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newUserServiceAdminDeleteUserArgs() interface{} {
	return user.NewUserServiceAdminDeleteUserArgs()
}

func newUserServiceAdminDeleteUserResult() interface{} {
	return user.NewUserServiceAdminDeleteUserResult()
}

func adminBroadcastHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceAdminBroadcastArgs)
	realResult := result.(*user.UserServiceAdminBroadcastResult)
	success, err := handler.(user.UserService).AdminBroadcast(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newUserServiceAdminBroadcastArgs() interface{} {
	return user.NewUserServiceAdminBroadcastArgs()
}

func newUserServiceAdminBroadcastResult() interface{} {
	return user.NewUserServiceAdminBroadcastResult()
}

func countAllHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	_ = arg.(*user.UserServiceCountAllArgs)
	realResult := result.(*user.UserServiceCountAllResult)
	success, err := handler.(user.UserService).CountAll(ctx)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newUserServiceCountAllArgs() interface{} {
	return user.NewUserServiceCountAllArgs()
}

func newUserServiceCountAllResult() interface{} {
	return user.NewUserServiceCountAllResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) SendCode(ctx context.Context, email string) (r *user.SendCodeResp, err error) {
	var _args user.UserServiceSendCodeArgs
	_args.Email = email
	var _result user.UserServiceSendCodeResult
	if err = p.c.Call(ctx, "SendCode", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Register(ctx context.Context, req *user.RegisterReq) (r *user.AuthResp, err error) {
	var _args user.UserServiceRegisterArgs
	_args.Req = req
	var _result user.UserServiceRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Login(ctx context.Context, req *user.LoginReq) (r *user.AuthResp, err error) {
	var _args user.UserServiceLoginArgs
	_args.Req = req
	var _result user.UserServiceLoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SocialLogin(ctx context.Context, provider string) (r *user.AuthResp, err error) {
	var _args user.UserServiceSocialLoginArgs
	_args.Provider = provider
	var _result user.UserServiceSocialLoginResult
	if err = p.c.Call(ctx, "SocialLogin", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ResetPassword(ctx context.Context, req *user.ResetPasswordReq) (r bool, err error) {
	var _args user.UserServiceResetPasswordArgs
	_args.Req = req
	var _result user.UserServiceResetPasswordResult
	if err = p.c.Call(ctx, "ResetPassword", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserByID(ctx context.Context, id int64) (r *user.User, err error) {
	var _args user.UserServiceGetUserByIDArgs
	_args.Id = id
	var _result user.UserServiceGetUserByIDResult
	if err = p.c.Call(ctx, "GetUserByID", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUsersByIDs(ctx context.Context, ids []int64) (r []*user.User, err error) {
	var _args user.UserServiceGetUsersByIDsArgs
	_args.Ids = ids
	var _result user.UserServiceGetUsersByIDsResult
	if err = p.c.Call(ctx, "GetUsersByIDs", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateProfile(ctx context.Context, req *user.UpdateProfileReq) (r *user.User, err error) {
	var _args user.UserServiceUpdateProfileArgs
	_args.Req = req
	var _result user.UserServiceUpdateProfileResult
	if err = p.c.Call(ctx, "UpdateProfile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdatePassword(ctx context.Context, req *user.UpdatePasswordReq) (r bool, err error) {
	var _args user.UserServiceUpdatePasswordArgs
	_args.Req = req
	var _result user.UserServiceUpdatePasswordResult
	if err = p.c.Call(ctx, "UpdatePassword", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetNotifications(ctx context.Context, req *user.GetListReq) (r *user.PaginatedResp, err error) {
	var _args user.UserServiceGetNotificationsArgs
	_args.Req = req
	var _result user.UserServiceGetNotificationsResult
	if err = p.c.Call(ctx, "GetNotifications", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ReadNotification(ctx context.Context, userId int64, notifId int64) (r bool, err error) {
	var _args user.UserServiceReadNotificationArgs
	_args.UserId = userId
	_args.NotifId = notifId
	var _result user.UserServiceReadNotificationResult
	if err = p.c.Call(ctx, "ReadNotification", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateNotification(ctx context.Context, req *user.CreateNotificationReq) (r bool, err error) {
	var _args user.UserServiceCreateNotificationArgs
	_args.Req = req
	var _result user.UserServiceCreateNotificationResult
	if err = p.c.Call(ctx, "CreateNotification", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetInteractions(ctx context.Context, req *user.GetListReq) (r *user.PaginatedResp, err error) {
	var _args user.UserServiceGetInteractionsArgs
	_args.Req = req
	var _result user.UserServiceGetInteractionsResult
	if err = p.c.Call(ctx, "GetInteractions", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateInteraction(ctx context.Context, req *user.CreateInteractionReq) (r bool, err error) {
	var _args user.UserServiceCreateInteractionArgs
	_args.Req = req
	var _result user.UserServiceCreateInteractionResult
	if err = p.c.Call(ctx, "CreateInteraction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AdminListUsers(ctx context.Context, req *user.AdminListUsersReq) (r *user.PaginatedResp, err error) {
	var _args user.UserServiceAdminListUsersArgs
	_args.Req = req
	var _result user.UserServiceAdminListUsersResult
	if err = p.c.Call(ctx, "AdminListUsers", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AdminGetUser(ctx context.Context, id int64) (r *user.User, err error) {
	var _args user.UserServiceAdminGetUserArgs
	_args.Id = id
	var _result user.UserServiceAdminGetUserResult
	if err = p.c.Call(ctx, "AdminGetUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AdminUpdateUser(ctx context.Context, req *user.AdminUpdateUserReq) (r *user.User, err error) {
	var _args user.UserServiceAdminUpdateUserArgs
	_args.Req = req
	var _result user.UserServiceAdminUpdateUserResult
	if err = p.c.Call(ctx, "AdminUpdateUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AdminDeleteUser(ctx context.Context, id int64) (r bool, err error) {
	var _args user.UserServiceAdminDeleteUserArgs
	_args.Id = id
	var _result user.UserServiceAdminDeleteUserResult
	if err = p.c.Call(ctx, "AdminDeleteUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AdminBroadcast(ctx context.Context, req *user.BroadcastReq) (r int32, err error) {
	var _args user.UserServiceAdminBroadcastArgs
	_args.Req = req
	var _result user.UserServiceAdminBroadcastResult
	if err = p.c.Call(ctx, "AdminBroadcast", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CountAll(ctx context.Context) (r int64, err error) {
	var _args user.UserServiceCountAllArgs
	var _result user.UserServiceCountAllResult
	if err = p.c.Call(ctx, "CountAll", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
