// Code generated by Kitex v0.16.3. DO NOT EDIT.

package voiceservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	voice "parrot-backend-go/kitex_gen/voice"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ListPublic(ctx context.Context, req *voice.ListPublicReq, callOptions ...callopt.Option) (r []*voice.Voice, err error)
	ListByUser(ctx context.Context, userId int64, callOptions ...callopt.Option) (r []*voice.Voice, err error)
	Create(ctx context.Context, req *voice.CreateVoiceReq, callOptions ...callopt.Option) (r *voice.Voice, err error)
	UpdateVisibility(ctx context.Context, req *voice.UpdateVisibilityReq, callOptions ...callopt.Option) (r bool, err error)
	Delete(ctx context.Context, req *voice.DeleteVoiceReq, callOptions ...callopt.Option) (r bool, err error)
	DescribeAI(ctx context.Context, req *voice.DescribeReq, callOptions ...callopt.Option) (r string, err error)
	GetRankings(ctx context.Context, req *voice.RankingsReq, callOptions ...callopt.Option) (r *voice.PaginatedVoices, err error)
	IncrementStat(ctx context.Context, req *voice.IncrementStatReq, callOptions ...callopt.Option) (r *voice.Voice, err error)
	AdminList(ctx context.Context, req *voice.AdminListVoicesReq, callOptions ...callopt.Option) (r *voice.PaginatedVoices, err error)
	AdminUpdate(ctx context.Context, req *voice.AdminUpdateVoiceReq, callOptions ...callopt.Option) (r *voice.Voice, err error)
	AdminDelete(ctx context.Context, id int64, callOptions ...callopt.Option) (r bool, err error)
	CountAll(ctx context.Context, callOptions ...callopt.Option) (r int64, err error)
	CountByVisibility(ctx context.Context, visibility string, callOptions ...callopt.Option) (r int64, err error)
	ValidateForUser(ctx context.Context, req *voice.ValidateVoiceReq, callOptions ...callopt.Option) (r *voice.Voice, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kVoiceServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kVoiceServiceClient struct {
	*kClient
}

func (p *kVoiceServiceClient) ListPublic(ctx context.Context, req *voice.ListPublicReq, callOptions ...callopt.Option) (r []*voice.Voice, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListPublic(ctx, req)
}

func (p *kVoiceServiceClient) ListByUser(ctx context.Context, userId int64, callOptions ...callopt.Option) (r []*voice.Voice, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListByUser(ctx, userId)
}

func (p *kVoiceServiceClient) Create(ctx context.Context, req *voice.CreateVoiceReq, callOptions ...callopt.Option) (r *voice.Voice, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Create(ctx, req)
}

func (p *kVoiceServiceClient) UpdateVisibility(ctx context.Context, req *voice.UpdateVisibilityReq, callOptions ...callopt.Option) (r bool, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateVisibility(ctx, req)
}

func (p *kVoiceServiceClient) Delete(ctx context.Context, req *voice.DeleteVoiceReq, callOptions ...callopt.Option) (r bool, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Delete(ctx, req)
}

func (p *kVoiceServiceClient) DescribeAI(ctx context.Context, req *voice.DescribeReq, callOptions ...callopt.Option) (r string, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DescribeAI(ctx, req)
}

func (p *kVoiceServiceClient) GetRankings(ctx context.Context, req *voice.RankingsReq, callOptions ...callopt.Option) (r *voice.PaginatedVoices, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRankings(ctx, req)
}

func (p *kVoiceServiceClient) IncrementStat(ctx context.Context, req *voice.IncrementStatReq, callOptions ...callopt.Option) (r *voice.Voice, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.IncrementStat(ctx, req)
}

func (p *kVoiceServiceClient) AdminList(ctx context.Context, req *voice.AdminListVoicesReq, callOptions ...callopt.Option) (r *voice.PaginatedVoices, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AdminList(ctx, req)
}

func (p *kVoiceServiceClient) AdminUpdate(ctx context.Context, req *voice.AdminUpdateVoiceReq, callOptions ...callopt.Option) (r *voice.Voice, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AdminUpdate(ctx, req)
}

func (p *kVoiceServiceClient) AdminDelete(ctx context.Context, id int64, callOptions ...callopt.Option) (r bool, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AdminDelete(ctx, id)
}

func (p *kVoiceServiceClient) CountAll(ctx context.Context, callOptions ...callopt.Option) (r int64, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CountAll(ctx)
}

func (p *kVoiceServiceClient) CountByVisibility(ctx context.Context, visibility string, callOptions ...callopt.Option) (r int64, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CountByVisibility(ctx, visibility)
}

func (p *kVoiceServiceClient) ValidateForUser(ctx context.Context, req *voice.ValidateVoiceReq, callOptions ...callopt.Option) (r *voice.Voice, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ValidateForUser(ctx, req)
}
