// Code generated by Kitex v0.16.3. DO NOT EDIT.

package voiceservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	voice "parrot-backend-go/kitex_gen/voice"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ListPublic": kitex.NewMethodInfo(
		listPublicHandler,
		newVoiceServiceListPublicArgs,
		newVoiceServiceListPublicResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListByUser": kitex.NewMethodInfo(
		listByUserHandler,
		newVoiceServiceListByUserArgs,
		newVoiceServiceListByUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Create": kitex.NewMethodInfo(
		createHandler,
		newVoiceServiceCreateArgs,
		newVoiceServiceCreateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateVisibility": kitex.NewMethodInfo(
		updateVisibilityHandler,
		newVoiceServiceUpdateVisibilityArgs,
		newVoiceServiceUpdateVisibilityResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Delete": kitex.NewMethodInfo(
		deleteHandler,
		newVoiceServiceDeleteArgs,
		newVoiceServiceDeleteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DescribeAI": kitex.NewMethodInfo(
		describeAIHandler,
		newVoiceServiceDescribeAIArgs,
		newVoiceServiceDescribeAIResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetRankings": kitex.NewMethodInfo(
		getRankingsHandler,
		newVoiceServiceGetRankingsArgs,
		newVoiceServiceGetRankingsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"IncrementStat": kitex.NewMethodInfo(
		incrementStatHandler,
		newVoiceServiceIncrementStatArgs,
		newVoiceServiceIncrementStatResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AdminList": kitex.NewMethodInfo(
		adminListHandler,
		newVoiceServiceAdminListArgs,
		newVoiceServiceAdminListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AdminUpdate": kitex.NewMethodInfo(
		adminUpdateHandler,
		newVoiceServiceAdminUpdateArgs,
		newVoiceServiceAdminUpdateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AdminDelete": kitex.NewMethodInfo(
		adminDeleteHandler,
		newVoiceServiceAdminDeleteArgs,
		newVoiceServiceAdminDeleteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CountAll": kitex.NewMethodInfo(
		countAllHandler,
		newVoiceServiceCountAllArgs,
		newVoiceServiceCountAllResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CountByVisibility": kitex.NewMethodInfo(
		countByVisibilityHandler,
		newVoiceServiceCountByVisibilityArgs,
		newVoiceServiceCountByVisibilityResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ValidateForUser": kitex.NewMethodInfo(
		validateForUserHandler,
		newVoiceServiceValidateForUserArgs,
		newVoiceServiceValidateForUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	voiceServiceServiceInfo                = NewServiceInfo()
	voiceServiceServiceInfoForClient       = NewServiceInfoForClient()
	voiceServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return voiceServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return voiceServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return voiceServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "VoiceService"
	handlerType := (*voice.VoiceService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "voice",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func listPublicHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*voice.VoiceServiceListPublicArgs)
	realResult := result.(*voice.VoiceServiceListPublicResult)
	success, err := handler.(voice.VoiceService).ListPublic(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVoiceServiceListPublicArgs() interface{} {
	return voice.NewVoiceServiceListPublicArgs()
}

func newVoiceServiceListPublicResult() interface{} {
	return voice.NewVoiceServiceListPublicResult()
}

func listByUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*voice.VoiceServiceListByUserArgs)
	realResult := result.(*voice.VoiceServiceListByUserResult)
	success, err := handler.(voice.VoiceService).ListByUser(ctx, realArg.UserId)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVoiceServiceListByUserArgs() interface{} {
	return voice.NewVoiceServiceListByUserArgs()
}

func newVoiceServiceListByUserResult() interface{} {
	return voice.NewVoiceServiceListByUserResult()
}

func createHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*voice.VoiceServiceCreateArgs)
	realResult := result.(*voice.VoiceServiceCreateResult)
	success, err := handler.(voice.VoiceService).Create(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVoiceServiceCreateArgs() interface{} {
	return voice.NewVoiceServiceCreateArgs()
}

func newVoiceServiceCreateResult() interface{} {
	return voice.NewVoiceServiceCreateResult()
}

func updateVisibilityHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*voice.VoiceServiceUpdateVisibilityArgs)
	realResult := result.(*voice.VoiceServiceUpdateVisibilityResult)
	success, err := handler.(voice.VoiceService).UpdateVisibility(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newVoiceServiceUpdateVisibilityArgs() interface{} {
	return voice.NewVoiceServiceUpdateVisibilityArgs()
}

func newVoiceServiceUpdateVisibilityResult() interface{} {
	return voice.NewVoiceServiceUpdateVisibilityResult()
}

func deleteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*voice.VoiceServiceDeleteArgs)
	realResult := result.(*voice.VoiceServiceDeleteResult)
	success, err := handler.(voice.VoiceService).Delete(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newVoiceServiceDeleteArgs() interface{} {
	return voice.NewVoiceServiceDeleteArgs()
}

func newVoiceServiceDeleteResult() interface{} {
	return voice.NewVoiceServiceDeleteResult()
}

func describeAIHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*voice.VoiceServiceDescribeAIArgs)
	realResult := result.(*voice.VoiceServiceDescribeAIResult)
	success, err := handler.(voice.VoiceService).DescribeAI(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newVoiceServiceDescribeAIArgs() interface{} {
	return voice.NewVoiceServiceDescribeAIArgs()
}

func newVoiceServiceDescribeAIResult() interface{} {
	return voice.NewVoiceServiceDescribeAIResult()
}

func getRankingsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*voice.VoiceServiceGetRankingsArgs)
	realResult := result.(*voice.VoiceServiceGetRankingsResult)
	success, err := handler.(voice.VoiceService).GetRankings(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVoiceServiceGetRankingsArgs() interface{} {
	return voice.NewVoiceServiceGetRankingsArgs()
}

func newVoiceServiceGetRankingsResult() interface{} {
	return voice.NewVoiceServiceGetRankingsResult()
}

func incrementStatHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*voice.VoiceServiceIncrementStatArgs)
	realResult := result.(*voice.VoiceServiceIncrementStatResult)
	success, err := handler.(voice.VoiceService).IncrementStat(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVoiceServiceIncrementStatArgs() interface{} {
	return voice.NewVoiceServiceIncrementStatArgs()
}

func newVoiceServiceIncrementStatResult() interface{} {
	return voice.NewVoiceServiceIncrementStatResult()
}

func adminListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*voice.VoiceServiceAdminListArgs)
	realResult := result.(*voice.VoiceServiceAdminListResult)
	success, err := handler.(voice.VoiceService).AdminList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVoiceServiceAdminListArgs() interface{} {
	return voice.NewVoiceServiceAdminListArgs()
}

func newVoiceServiceAdminListResult() interface{} {
	return voice.NewVoiceServiceAdminListResult()
}

func adminUpdateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*voice.VoiceServiceAdminUpdateArgs)
	realResult := result.(*voice.VoiceServiceAdminUpdateResult)
	success, err := handler.(voice.VoiceService).AdminUpdate(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVoiceServiceAdminUpdateArgs() interface{} {
	return voice.NewVoiceServiceAdminUpdateArgs()
}

func newVoiceServiceAdminUpdateResult() interface{} {
	return voice.NewVoiceServiceAdminUpdateResult()
}

func adminDeleteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*voice.VoiceServiceAdminDeleteArgs)
	realResult := result.(*voice.VoiceServiceAdminDeleteResult)
	success, err := handler.(voice.VoiceService).AdminDelete(ctx, realArg.Id)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newVoiceServiceAdminDeleteArgs() interface{} {
	return voice.NewVoiceServiceAdminDeleteArgs()
}

func newVoiceServiceAdminDeleteResult() interface{} {
	return voice.NewVoiceServiceAdminDeleteResult()
}

func countAllHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	_ = arg.(*voice.VoiceServiceCountAllArgs)
	realResult := result.(*voice.VoiceServiceCountAllResult)
	success, err := handler.(voice.VoiceService).CountAll(ctx)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newVoiceServiceCountAllArgs() interface{} {
	return voice.NewVoiceServiceCountAllArgs()
}

func newVoiceServiceCountAllResult() interface{} {
	return voice.NewVoiceServiceCountAllResult()
}

func countByVisibilityHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*voice.VoiceServiceCountByVisibilityArgs)
	realResult := result.(*voice.VoiceServiceCountByVisibilityResult)
	success, err := handler.(voice.VoiceService).CountByVisibility(ctx, realArg.Visibility)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newVoiceServiceCountByVisibilityArgs() interface{} {
	return voice.NewVoiceServiceCountByVisibilityArgs()
}

func newVoiceServiceCountByVisibilityResult() interface{} {
	return voice.NewVoiceServiceCountByVisibilityResult()
}

func validateForUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*voice.VoiceServiceValidateForUserArgs)
	realResult := result.(*voice.VoiceServiceValidateForUserResult)
	success, err := handler.(voice.VoiceService).ValidateForUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVoiceServiceValidateForUserArgs() interface{} {
	return voice.NewVoiceServiceValidateForUserArgs()
}

func newVoiceServiceValidateForUserResult() interface{} {
	return voice.NewVoiceServiceValidateForUserResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ListPublic(ctx context.Context, req *voice.ListPublicReq) (r []*voice.Voice, err error) {
	var _args voice.VoiceServiceListPublicArgs
	_args.Req = req
	var _result voice.VoiceServiceListPublicResult
	if err = p.c.Call(ctx, "ListPublic", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListByUser(ctx context.Context, userId int64) (r []*voice.Voice, err error) {
	var _args voice.VoiceServiceListByUserArgs
	_args.UserId = userId
	var _result voice.VoiceServiceListByUserResult
	if err = p.c.Call(ctx, "ListByUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Create(ctx context.Context, req *voice.CreateVoiceReq) (r *voice.Voice, err error) {
	var _args voice.VoiceServiceCreateArgs
	_args.Req = req
	var _result voice.VoiceServiceCreateResult
	if err = p.c.Call(ctx, "Create", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateVisibility(ctx context.Context, req *voice.UpdateVisibilityReq) (r bool, err error) {
	var _args voice.VoiceServiceUpdateVisibilityArgs
	_args.Req = req
	var _result voice.VoiceServiceUpdateVisibilityResult
	if err = p.c.Call(ctx, "UpdateVisibility", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Delete(ctx context.Context, req *voice.DeleteVoiceReq) (r bool, err error) {
	var _args voice.VoiceServiceDeleteArgs
	_args.Req = req
	var _result voice.VoiceServiceDeleteResult
	if err = p.c.Call(ctx, "Delete", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DescribeAI(ctx context.Context, req *voice.DescribeReq) (r string, err error) {
	var _args voice.VoiceServiceDescribeAIArgs
	_args.Req = req
	var _result voice.VoiceServiceDescribeAIResult
	if err = p.c.Call(ctx, "DescribeAI", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetRankings(ctx context.Context, req *voice.RankingsReq) (r *voice.PaginatedVoices, err error) {
	var _args voice.VoiceServiceGetRankingsArgs
	_args.Req = req
	var _result voice.VoiceServiceGetRankingsResult
	if err = p.c.Call(ctx, "GetRankings", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) IncrementStat(ctx context.Context, req *voice.IncrementStatReq) (r *voice.Voice, err error) {
	var _args voice.VoiceServiceIncrementStatArgs
	_args.Req = req
	var _result voice.VoiceServiceIncrementStatResult
	if err = p.c.Call(ctx, "IncrementStat", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AdminList(ctx context.Context, req *voice.AdminListVoicesReq) (r *voice.PaginatedVoices, err error) {
	var _args voice.VoiceServiceAdminListArgs
	_args.Req = req
	var _result voice.VoiceServiceAdminListResult
	if err = p.c.Call(ctx, "AdminList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AdminUpdate(ctx context.Context, req *voice.AdminUpdateVoiceReq) (r *voice.Voice, err error) {
	var _args voice.VoiceServiceAdminUpdateArgs
	_args.Req = req
	var _result voice.VoiceServiceAdminUpdateResult
	if err = p.c.Call(ctx, "AdminUpdate", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AdminDelete(ctx context.Context, id int64) (r bool, err error) {
	var _args voice.VoiceServiceAdminDeleteArgs
	_args.Id = id
	var _result voice.VoiceServiceAdminDeleteResult
	if err = p.c.Call(ctx, "AdminDelete", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CountAll(ctx context.Context) (r int64, err error) {
	var _args voice.VoiceServiceCountAllArgs
	var _result voice.VoiceServiceCountAllResult
	if err = p.c.Call(ctx, "CountAll", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CountByVisibility(ctx context.Context, visibility string) (r int64, err error) {
	var _args voice.VoiceServiceCountByVisibilityArgs
	_args.Visibility = visibility
	var _result voice.VoiceServiceCountByVisibilityResult
	if err = p.c.Call(ctx, "CountByVisibility", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ValidateForUser(ctx context.Context, req *voice.ValidateVoiceReq) (r *voice.Voice, err error) {
	var _args voice.VoiceServiceValidateForUserArgs
	_args.Req = req
	var _result voice.VoiceServiceValidateForUserResult
	if err = p.c.Call(ctx, "ValidateForUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
