// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package voice

import (
	"context"
	"fmt"
)

type Voice struct {
	Id             int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	UserId         int64  `thrift:"userId,2" frugal:"2,default,i64" json:"userId"`
	Name           string `thrift:"name,3" frugal:"3,default,string" json:"name"`
	Description    string `thrift:"description,4" frugal:"4,default,string" json:"description"`
	Tag            string `thrift:"tag,5" frugal:"5,default,string" json:"tag"`
	Language       string `thrift:"language,6" frugal:"6,default,string" json:"language"`
	Visibility     string `thrift:"visibility,7" frugal:"7,default,string" json:"visibility"`
	CoverUrl       string `thrift:"coverUrl,8" frugal:"8,default,string" json:"coverUrl"`
	SampleAudioUrl string `thrift:"sampleAudioUrl,9" frugal:"9,default,string" json:"sampleAudioUrl"`
	PlayCount      int32  `thrift:"playCount,10" frugal:"10,default,i32" json:"playCount"`
	LikeCount      int32  `thrift:"likeCount,11" frugal:"11,default,i32" json:"likeCount"`
	FavoriteCount  int32  `thrift:"favoriteCount,12" frugal:"12,default,i32" json:"favoriteCount"`
	UseCount       int32  `thrift:"useCount,13" frugal:"13,default,i32" json:"useCount"`
	CreatedAt      string `thrift:"createdAt,14" frugal:"14,default,string" json:"createdAt"`
}

func NewVoice() *Voice {
	return &Voice{}
}

func (p *Voice) InitDefault() {
}

func (p *Voice) GetId() (v int64) {
	return p.Id
}

func (p *Voice) GetUserId() (v int64) {
	return p.UserId
}

func (p *Voice) GetName() (v string) {
	return p.Name
}

func (p *Voice) GetDescription() (v string) {
	return p.Description
}

func (p *Voice) GetTag() (v string) {
	return p.Tag
}

func (p *Voice) GetLanguage() (v string) {
	return p.Language
}

func (p *Voice) GetVisibility() (v string) {
	return p.Visibility
}

func (p *Voice) GetCoverUrl() (v string) {
	return p.CoverUrl
}

func (p *Voice) GetSampleAudioUrl() (v string) {
	return p.SampleAudioUrl
}

func (p *Voice) GetPlayCount() (v int32) {
	return p.PlayCount
}

func (p *Voice) GetLikeCount() (v int32) {
	return p.LikeCount
}

func (p *Voice) GetFavoriteCount() (v int32) {
	return p.FavoriteCount
}

func (p *Voice) GetUseCount() (v int32) {
	return p.UseCount
}

func (p *Voice) GetCreatedAt() (v string) {
	return p.CreatedAt
}
func (p *Voice) SetId(val int64) {
	p.Id = val
}
func (p *Voice) SetUserId(val int64) {
	p.UserId = val
}
func (p *Voice) SetName(val string) {
	p.Name = val
}
func (p *Voice) SetDescription(val string) {
	p.Description = val
}
func (p *Voice) SetTag(val string) {
	p.Tag = val
}
func (p *Voice) SetLanguage(val string) {
	p.Language = val
}
func (p *Voice) SetVisibility(val string) {
	p.Visibility = val
}
func (p *Voice) SetCoverUrl(val string) {
	p.CoverUrl = val
}
func (p *Voice) SetSampleAudioUrl(val string) {
	p.SampleAudioUrl = val
}
func (p *Voice) SetPlayCount(val int32) {
	p.PlayCount = val
}
func (p *Voice) SetLikeCount(val int32) {
	p.LikeCount = val
}
func (p *Voice) SetFavoriteCount(val int32) {
	p.FavoriteCount = val
}
func (p *Voice) SetUseCount(val int32) {
	p.UseCount = val
}
func (p *Voice) SetCreatedAt(val string) {
	p.CreatedAt = val
}

func (p *Voice) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Voice(%+v)", *p)
}

var fieldIDToName_Voice = map[int16]string{
	1:  "id",
	2:  "userId",
	3:  "name",
	4:  "description",
	5:  "tag",
	6:  "language",
	7:  "visibility",
	8:  "coverUrl",
	9:  "sampleAudioUrl",
	10: "playCount",
	11: "likeCount",
	12: "favoriteCount",
	13: "useCount",
	14: "createdAt",
}

type PaginatedVoices struct {
	Items    []*Voice `thrift:"items,1" frugal:"1,default,list<Voice>" json:"items"`
	Total    int64    `thrift:"total,2" frugal:"2,default,i64" json:"total"`
	Page     int32    `thrift:"page,3" frugal:"3,default,i32" json:"page"`
	PageSize int32    `thrift:"pageSize,4" frugal:"4,default,i32" json:"pageSize"`
}

func NewPaginatedVoices() *PaginatedVoices {
	return &PaginatedVoices{}
}

func (p *PaginatedVoices) InitDefault() {
}

func (p *PaginatedVoices) GetItems() (v []*Voice) {
	return p.Items
}

func (p *PaginatedVoices) GetTotal() (v int64) {
	return p.Total
}

func (p *PaginatedVoices) GetPage() (v int32) {
	return p.Page
}

func (p *PaginatedVoices) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *PaginatedVoices) SetItems(val []*Voice) {
	p.Items = val
}
func (p *PaginatedVoices) SetTotal(val int64) {
	p.Total = val
}
func (p *PaginatedVoices) SetPage(val int32) {
	p.Page = val
}
func (p *PaginatedVoices) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *PaginatedVoices) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PaginatedVoices(%+v)", *p)
}

var fieldIDToName_PaginatedVoices = map[int16]string{
	1: "items",
	2: "total",
	3: "page",
	4: "pageSize",
}

type ListPublicReq struct {
	Search string `thrift:"search,1" frugal:"1,default,string" json:"search"`
	Filter string `thrift:"filter,2" frugal:"2,default,string" json:"filter"`
}

func NewListPublicReq() *ListPublicReq {
	return &ListPublicReq{}
}

func (p *ListPublicReq) InitDefault() {
}

func (p *ListPublicReq) GetSearch() (v string) {
	return p.Search
}

func (p *ListPublicReq) GetFilter() (v string) {
	return p.Filter
}
func (p *ListPublicReq) SetSearch(val string) {
	p.Search = val
}
func (p *ListPublicReq) SetFilter(val string) {
	p.Filter = val
}

func (p *ListPublicReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListPublicReq(%+v)", *p)
}

var fieldIDToName_ListPublicReq = map[int16]string{
	1: "search",
	2: "filter",
}

type CreateVoiceReq struct {
	UserId         int64  `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	Name           string `thrift:"name,2" frugal:"2,default,string" json:"name"`
	Description    string `thrift:"description,3" frugal:"3,default,string" json:"description"`
	Tag            string `thrift:"tag,4" frugal:"4,default,string" json:"tag"`
	Visibility     string `thrift:"visibility,5" frugal:"5,default,string" json:"visibility"`
	Language       string `thrift:"language,6" frugal:"6,default,string" json:"language"`
	CoverUrl       string `thrift:"coverUrl,7" frugal:"7,default,string" json:"coverUrl"`
	SampleAudioUrl string `thrift:"sampleAudioUrl,8" frugal:"8,default,string" json:"sampleAudioUrl"`
}

func NewCreateVoiceReq() *CreateVoiceReq {
	return &CreateVoiceReq{}
}

func (p *CreateVoiceReq) InitDefault() {
}

func (p *CreateVoiceReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *CreateVoiceReq) GetName() (v string) {
	return p.Name
}

func (p *CreateVoiceReq) GetDescription() (v string) {
	return p.Description
}

func (p *CreateVoiceReq) GetTag() (v string) {
	return p.Tag
}

func (p *CreateVoiceReq) GetVisibility() (v string) {
	return p.Visibility
}

func (p *CreateVoiceReq) GetLanguage() (v string) {
	return p.Language
}

func (p *CreateVoiceReq) GetCoverUrl() (v string) {
	return p.CoverUrl
}

func (p *CreateVoiceReq) GetSampleAudioUrl() (v string) {
	return p.SampleAudioUrl
}
func (p *CreateVoiceReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *CreateVoiceReq) SetName(val string) {
	p.Name = val
}
func (p *CreateVoiceReq) SetDescription(val string) {
	p.Description = val
}
func (p *CreateVoiceReq) SetTag(val string) {
	p.Tag = val
}
func (p *CreateVoiceReq) SetVisibility(val string) {
	p.Visibility = val
}
func (p *CreateVoiceReq) SetLanguage(val string) {
	p.Language = val
}
func (p *CreateVoiceReq) SetCoverUrl(val string) {
	p.CoverUrl = val
}
func (p *CreateVoiceReq) SetSampleAudioUrl(val string) {
	p.SampleAudioUrl = val
}

func (p *CreateVoiceReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateVoiceReq(%+v)", *p)
}

var fieldIDToName_CreateVoiceReq = map[int16]string{
	1: "userId",
	2: "name",
	3: "description",
	4: "tag",
	5: "visibility",
	6: "language",
	7: "coverUrl",
	8: "sampleAudioUrl",
}

type UpdateVisibilityReq struct {
	Id         int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	UserId     int64  `thrift:"userId,2" frugal:"2,default,i64" json:"userId"`
	Visibility string `thrift:"visibility,3" frugal:"3,default,string" json:"visibility"`
}

func NewUpdateVisibilityReq() *UpdateVisibilityReq {
	return &UpdateVisibilityReq{}
}

func (p *UpdateVisibilityReq) InitDefault() {
}

func (p *UpdateVisibilityReq) GetId() (v int64) {
	return p.Id
}

func (p *UpdateVisibilityReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *UpdateVisibilityReq) GetVisibility() (v string) {
	return p.Visibility
}
func (p *UpdateVisibilityReq) SetId(val int64) {
	p.Id = val
}
func (p *UpdateVisibilityReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *UpdateVisibilityReq) SetVisibility(val string) {
	p.Visibility = val
}

func (p *UpdateVisibilityReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateVisibilityReq(%+v)", *p)
}

var fieldIDToName_UpdateVisibilityReq = map[int16]string{
	1: "id",
	2: "userId",
	3: "visibility",
}

type DeleteVoiceReq struct {
	Id     int64 `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	UserId int64 `thrift:"userId,2" frugal:"2,default,i64" json:"userId"`
}

func NewDeleteVoiceReq() *DeleteVoiceReq {
	return &DeleteVoiceReq{}
}

func (p *DeleteVoiceReq) InitDefault() {
}

func (p *DeleteVoiceReq) GetId() (v int64) {
	return p.Id
}

func (p *DeleteVoiceReq) GetUserId() (v int64) {
	return p.UserId
}
func (p *DeleteVoiceReq) SetId(val int64) {
	p.Id = val
}
func (p *DeleteVoiceReq) SetUserId(val int64) {
	p.UserId = val
}

func (p *DeleteVoiceReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteVoiceReq(%+v)", *p)
}

var fieldIDToName_DeleteVoiceReq = map[int16]string{
	1: "id",
	2: "userId",
}

type DescribeReq struct {
	Name   string `thrift:"name,1" frugal:"1,default,string" json:"name"`
	Prompt string `thrift:"prompt,2" frugal:"2,default,string" json:"prompt"`
	Model  string `thrift:"model,3" frugal:"3,default,string" json:"model"`
}

func NewDescribeReq() *DescribeReq {
	return &DescribeReq{}
}

func (p *DescribeReq) InitDefault() {
}

func (p *DescribeReq) GetName() (v string) {
	return p.Name
}

func (p *DescribeReq) GetPrompt() (v string) {
	return p.Prompt
}

func (p *DescribeReq) GetModel() (v string) {
	return p.Model
}
func (p *DescribeReq) SetName(val string) {
	p.Name = val
}
func (p *DescribeReq) SetPrompt(val string) {
	p.Prompt = val
}
func (p *DescribeReq) SetModel(val string) {
	p.Model = val
}

func (p *DescribeReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DescribeReq(%+v)", *p)
}

var fieldIDToName_DescribeReq = map[int16]string{
	1: "name",
	2: "prompt",
	3: "model",
}

type IncrementStatReq struct {
	Id    int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Field string `thrift:"field,2" frugal:"2,default,string" json:"field"`
}

func NewIncrementStatReq() *IncrementStatReq {
	return &IncrementStatReq{}
}

func (p *IncrementStatReq) InitDefault() {
}

func (p *IncrementStatReq) GetId() (v int64) {
	return p.Id
}

func (p *IncrementStatReq) GetField() (v string) {
	return p.Field
}
func (p *IncrementStatReq) SetId(val int64) {
	p.Id = val
}
func (p *IncrementStatReq) SetField(val string) {
	p.Field = val
}

func (p *IncrementStatReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IncrementStatReq(%+v)", *p)
}

var fieldIDToName_IncrementStatReq = map[int16]string{
	1: "id",
	2: "field",
}

type RankingsReq struct {
	Page     int32 `thrift:"page,1" frugal:"1,default,i32" json:"page"`
	PageSize int32 `thrift:"pageSize,2" frugal:"2,default,i32" json:"pageSize"`
}

func NewRankingsReq() *RankingsReq {
	return &RankingsReq{}
}

func (p *RankingsReq) InitDefault() {
}

func (p *RankingsReq) GetPage() (v int32) {
	return p.Page
}

func (p *RankingsReq) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *RankingsReq) SetPage(val int32) {
	p.Page = val
}
func (p *RankingsReq) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *RankingsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RankingsReq(%+v)", *p)
}

var fieldIDToName_RankingsReq = map[int16]string{
	1: "page",
	2: "pageSize",
}

type AdminListVoicesReq struct {
	Visibility string `thrift:"visibility,1" frugal:"1,default,string" json:"visibility"`
	Page       int32  `thrift:"page,2" frugal:"2,default,i32" json:"page"`
	PageSize   int32  `thrift:"pageSize,3" frugal:"3,default,i32" json:"pageSize"`
}

func NewAdminListVoicesReq() *AdminListVoicesReq {
	return &AdminListVoicesReq{}
}

func (p *AdminListVoicesReq) InitDefault() {
}

func (p *AdminListVoicesReq) GetVisibility() (v string) {
	return p.Visibility
}

func (p *AdminListVoicesReq) GetPage() (v int32) {
	return p.Page
}

func (p *AdminListVoicesReq) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *AdminListVoicesReq) SetVisibility(val string) {
	p.Visibility = val
}
func (p *AdminListVoicesReq) SetPage(val int32) {
	p.Page = val
}
func (p *AdminListVoicesReq) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *AdminListVoicesReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdminListVoicesReq(%+v)", *p)
}

var fieldIDToName_AdminListVoicesReq = map[int16]string{
	1: "visibility",
	2: "page",
	3: "pageSize",
}

type AdminUpdateVoiceReq struct {
	Id         int64   `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Visibility *string `thrift:"visibility,2,optional" frugal:"2,optional,string" json:"visibility,omitempty"`
	Name       *string `thrift:"name,3,optional" frugal:"3,optional,string" json:"name,omitempty"`
	Tag        *string `thrift:"tag,4,optional" frugal:"4,optional,string" json:"tag,omitempty"`
}

func NewAdminUpdateVoiceReq() *AdminUpdateVoiceReq {
	return &AdminUpdateVoiceReq{}
}

func (p *AdminUpdateVoiceReq) InitDefault() {
}

func (p *AdminUpdateVoiceReq) GetId() (v int64) {
	return p.Id
}

var AdminUpdateVoiceReq_Visibility_DEFAULT string

func (p *AdminUpdateVoiceReq) GetVisibility() (v string) {
	if !p.IsSetVisibility() {
		return AdminUpdateVoiceReq_Visibility_DEFAULT
	}
	return *p.Visibility
}

var AdminUpdateVoiceReq_Name_DEFAULT string

func (p *AdminUpdateVoiceReq) GetName() (v string) {
	if !p.IsSetName() {
		return AdminUpdateVoiceReq_Name_DEFAULT
	}
	return *p.Name
}

var AdminUpdateVoiceReq_Tag_DEFAULT string

func (p *AdminUpdateVoiceReq) GetTag() (v string) {
	if !p.IsSetTag() {
		return AdminUpdateVoiceReq_Tag_DEFAULT
	}
	return *p.Tag
}
func (p *AdminUpdateVoiceReq) SetId(val int64) {
	p.Id = val
}
func (p *AdminUpdateVoiceReq) SetVisibility(val *string) {
	p.Visibility = val
}
func (p *AdminUpdateVoiceReq) SetName(val *string) {
	p.Name = val
}
func (p *AdminUpdateVoiceReq) SetTag(val *string) {
	p.Tag = val
}

func (p *AdminUpdateVoiceReq) IsSetVisibility() bool {
	return p.Visibility != nil
}

func (p *AdminUpdateVoiceReq) IsSetName() bool {
	return p.Name != nil
}

func (p *AdminUpdateVoiceReq) IsSetTag() bool {
	return p.Tag != nil
}

func (p *AdminUpdateVoiceReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdminUpdateVoiceReq(%+v)", *p)
}

var fieldIDToName_AdminUpdateVoiceReq = map[int16]string{
	1: "id",
	2: "visibility",
	3: "name",
	4: "tag",
}

type ValidateVoiceReq struct {
	Id     int64 `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	UserId int64 `thrift:"userId,2" frugal:"2,default,i64" json:"userId"`
}

func NewValidateVoiceReq() *ValidateVoiceReq {
	return &ValidateVoiceReq{}
}

func (p *ValidateVoiceReq) InitDefault() {
}

func (p *ValidateVoiceReq) GetId() (v int64) {
	return p.Id
}

func (p *ValidateVoiceReq) GetUserId() (v int64) {
	return p.UserId
}
func (p *ValidateVoiceReq) SetId(val int64) {
	p.Id = val
}
func (p *ValidateVoiceReq) SetUserId(val int64) {
	p.UserId = val
}

func (p *ValidateVoiceReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ValidateVoiceReq(%+v)", *p)
}

var fieldIDToName_ValidateVoiceReq = map[int16]string{
	1: "id",
	2: "userId",
}

type VoiceService interface {
	ListPublic(ctx context.Context, req *ListPublicReq) (r []*Voice, err error)

	ListByUser(ctx context.Context, userId int64) (r []*Voice, err error)

	Create(ctx context.Context, req *CreateVoiceReq) (r *Voice, err error)

	UpdateVisibility(ctx context.Context, req *UpdateVisibilityReq) (r bool, err error)

	Delete(ctx context.Context, req *DeleteVoiceReq) (r bool, err error)

	DescribeAI(ctx context.Context, req *DescribeReq) (r string, err error)

	GetRankings(ctx context.Context, req *RankingsReq) (r *PaginatedVoices, err error)

	IncrementStat(ctx context.Context, req *IncrementStatReq) (r *Voice, err error)

	AdminList(ctx context.Context, req *AdminListVoicesReq) (r *PaginatedVoices, err error)

	AdminUpdate(ctx context.Context, req *AdminUpdateVoiceReq) (r *Voice, err error)

	AdminDelete(ctx context.Context, id int64) (r bool, err error)

	CountAll(ctx context.Context) (r int64, err error)

	CountByVisibility(ctx context.Context, visibility string) (r int64, err error)

	ValidateForUser(ctx context.Context, req *ValidateVoiceReq) (r *Voice, err error)
}

type VoiceServiceListPublicArgs struct {
	Req *ListPublicReq `thrift:"req,1" frugal:"1,default,ListPublicReq" json:"req"`
}

func NewVoiceServiceListPublicArgs() *VoiceServiceListPublicArgs {
	return &VoiceServiceListPublicArgs{}
}

func (p *VoiceServiceListPublicArgs) InitDefault() {
}

var VoiceServiceListPublicArgs_Req_DEFAULT *ListPublicReq

func (p *VoiceServiceListPublicArgs) GetReq() (v *ListPublicReq) {
	if !p.IsSetReq() {
		return VoiceServiceListPublicArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VoiceServiceListPublicArgs) SetReq(val *ListPublicReq) {
	p.Req = val
}

func (p *VoiceServiceListPublicArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VoiceServiceListPublicArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VoiceServiceListPublicArgs(%+v)", *p)
}

var fieldIDToName_VoiceServiceListPublicArgs = map[int16]string{
	1: "req",
}

type VoiceServiceListPublicResult struct {
	Success []*Voice `thrift:"success,0,optional" frugal:"0,optional,list<Voice>" json:"success,omitempty"`
}

func NewVoiceServiceListPublicResult() *VoiceServiceListPublicResult {
	return &VoiceServiceListPublicResult{}
}

func (p *VoiceServiceListPublicResult) InitDefault() {
}

var VoiceServiceListPublicResult_Success_DEFAULT []*Voice

func (p *VoiceServiceListPublicResult) GetSuccess() (v []*Voice) {
	if !p.IsSetSuccess() {
		return VoiceServiceListPublicResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VoiceServiceListPublicResult) SetSuccess(x interface{}) {
	p.Success = x.([]*Voice)
}

func (p *VoiceServiceListPublicResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VoiceServiceListPublicResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VoiceServiceListPublicResult(%+v)", *p)
}

var fieldIDToName_VoiceServiceListPublicResult = map[int16]string{
	0: "success",
}

type VoiceServiceListByUserArgs struct {
	UserId int64 `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
}

func NewVoiceServiceListByUserArgs() *VoiceServiceListByUserArgs {
	return &VoiceServiceListByUserArgs{}
}

func (p *VoiceServiceListByUserArgs) InitDefault() {
}

func (p *VoiceServiceListByUserArgs) GetUserId() (v int64) {
	return p.UserId
}
func (p *VoiceServiceListByUserArgs) SetUserId(val int64) {
	p.UserId = val
}

func (p *VoiceServiceListByUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VoiceServiceListByUserArgs(%+v)", *p)
}

var fieldIDToName_VoiceServiceListByUserArgs = map[int16]string{
	1: "userId",
}

type VoiceServiceListByUserResult struct {
	Success []*Voice `thrift:"success,0,optional" frugal:"0,optional,list<Voice>" json:"success,omitempty"`
}

func NewVoiceServiceListByUserResult() *VoiceServiceListByUserResult {
	return &VoiceServiceListByUserResult{}
}

func (p *VoiceServiceListByUserResult) InitDefault() {
}

var VoiceServiceListByUserResult_Success_DEFAULT []*Voice

func (p *VoiceServiceListByUserResult) GetSuccess() (v []*Voice) {
	if !p.IsSetSuccess() {
		return VoiceServiceListByUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VoiceServiceListByUserResult) SetSuccess(x interface{}) {
	p.Success = x.([]*Voice)
}

func (p *VoiceServiceListByUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VoiceServiceListByUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VoiceServiceListByUserResult(%+v)", *p)
}

var fieldIDToName_VoiceServiceListByUserResult = map[int16]string{
	0: "success",
}

type VoiceServiceCreateArgs struct {
	Req *CreateVoiceReq `thrift:"req,1" frugal:"1,default,CreateVoiceReq" json:"req"`
}

func NewVoiceServiceCreateArgs() *VoiceServiceCreateArgs {
	return &VoiceServiceCreateArgs{}
}

func (p *VoiceServiceCreateArgs) InitDefault() {
}

var VoiceServiceCreateArgs_Req_DEFAULT *CreateVoiceReq

func (p *VoiceServiceCreateArgs) GetReq() (v *CreateVoiceReq) {
	if !p.IsSetReq() {
		return VoiceServiceCreateArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VoiceServiceCreateArgs) SetReq(val *CreateVoiceReq) {
	p.Req = val
}

func (p *VoiceServiceCreateArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VoiceServiceCreateArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VoiceServiceCreateArgs(%+v)", *p)
}

var fieldIDToName_VoiceServiceCreateArgs = map[int16]string{
	1: "req",
}

type VoiceServiceCreateResult struct {
	Success *Voice `thrift:"success,0,optional" frugal:"0,optional,Voice" json:"success,omitempty"`
}

func NewVoiceServiceCreateResult() *VoiceServiceCreateResult {
	return &VoiceServiceCreateResult{}
}

func (p *VoiceServiceCreateResult) InitDefault() {
}

var VoiceServiceCreateResult_Success_DEFAULT *Voice

func (p *VoiceServiceCreateResult) GetSuccess() (v *Voice) {
	if !p.IsSetSuccess() {
		return VoiceServiceCreateResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VoiceServiceCreateResult) SetSuccess(x interface{}) {
	p.Success = x.(*Voice)
}

func (p *VoiceServiceCreateResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VoiceServiceCreateResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VoiceServiceCreateResult(%+v)", *p)
}

var fieldIDToName_VoiceServiceCreateResult = map[int16]string{
	0: "success",
}

type VoiceServiceUpdateVisibilityArgs struct {
	Req *UpdateVisibilityReq `thrift:"req,1" frugal:"1,default,UpdateVisibilityReq" json:"req"`
}

func NewVoiceServiceUpdateVisibilityArgs() *VoiceServiceUpdateVisibilityArgs {
	return &VoiceServiceUpdateVisibilityArgs{}
}

func (p *VoiceServiceUpdateVisibilityArgs) InitDefault() {
}

var VoiceServiceUpdateVisibilityArgs_Req_DEFAULT *UpdateVisibilityReq

func (p *VoiceServiceUpdateVisibilityArgs) GetReq() (v *UpdateVisibilityReq) {
	if !p.IsSetReq() {
		return VoiceServiceUpdateVisibilityArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VoiceServiceUpdateVisibilityArgs) SetReq(val *UpdateVisibilityReq) {
	p.Req = val
}

func (p *VoiceServiceUpdateVisibilityArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VoiceServiceUpdateVisibilityArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VoiceServiceUpdateVisibilityArgs(%+v)", *p)
}

var fieldIDToName_VoiceServiceUpdateVisibilityArgs = map[int16]string{
	1: "req",
}

type VoiceServiceUpdateVisibilityResult struct {
	Success *bool `thrift:"success,0,optional" frugal:"0,optional,bool" json:"success,omitempty"`
}

func NewVoiceServiceUpdateVisibilityResult() *VoiceServiceUpdateVisibilityResult {
	return &VoiceServiceUpdateVisibilityResult{}
}

func (p *VoiceServiceUpdateVisibilityResult) InitDefault() {
}

var VoiceServiceUpdateVisibilityResult_Success_DEFAULT bool

func (p *VoiceServiceUpdateVisibilityResult) GetSuccess() (v bool) {
	if !p.IsSetSuccess() {
		return VoiceServiceUpdateVisibilityResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *VoiceServiceUpdateVisibilityResult) SetSuccess(x interface{}) {
	p.Success = x.(*bool)
}

func (p *VoiceServiceUpdateVisibilityResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VoiceServiceUpdateVisibilityResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VoiceServiceUpdateVisibilityResult(%+v)", *p)
}

var fieldIDToName_VoiceServiceUpdateVisibilityResult = map[int16]string{
	0: "success",
}

type VoiceServiceDeleteArgs struct {
	Req *DeleteVoiceReq `thrift:"req,1" frugal:"1,default,DeleteVoiceReq" json:"req"`
}

func NewVoiceServiceDeleteArgs() *VoiceServiceDeleteArgs {
	return &VoiceServiceDeleteArgs{}
}

func (p *VoiceServiceDeleteArgs) InitDefault() {
}

var VoiceServiceDeleteArgs_Req_DEFAULT *DeleteVoiceReq

func (p *VoiceServiceDeleteArgs) GetReq() (v *DeleteVoiceReq) {
	if !p.IsSetReq() {
		return VoiceServiceDeleteArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VoiceServiceDeleteArgs) SetReq(val *DeleteVoiceReq) {
	p.Req = val
}

func (p *VoiceServiceDeleteArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VoiceServiceDeleteArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VoiceServiceDeleteArgs(%+v)", *p)
}

var fieldIDToName_VoiceServiceDeleteArgs = map[int16]string{
	1: "req",
}

type VoiceServiceDeleteResult struct {
	Success *bool `thrift:"success,0,optional" frugal:"0,optional,bool" json:"success,omitempty"`
}

func NewVoiceServiceDeleteResult() *VoiceServiceDeleteResult {
	return &VoiceServiceDeleteResult{}
}

func (p *VoiceServiceDeleteResult) InitDefault() {
}

var VoiceServiceDeleteResult_Success_DEFAULT bool

func (p *VoiceServiceDeleteResult) GetSuccess() (v bool) {
	if !p.IsSetSuccess() {
		return VoiceServiceDeleteResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *VoiceServiceDeleteResult) SetSuccess(x interface{}) {
	p.Success = x.(*bool)
}

func (p *VoiceServiceDeleteResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VoiceServiceDeleteResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VoiceServiceDeleteResult(%+v)", *p)
}

var fieldIDToName_VoiceServiceDeleteResult = map[int16]string{
	0: "success",
}

type VoiceServiceDescribeAIArgs struct {
	Req *DescribeReq `thrift:"req,1" frugal:"1,default,DescribeReq" json:"req"`
}

func NewVoiceServiceDescribeAIArgs() *VoiceServiceDescribeAIArgs {
	return &VoiceServiceDescribeAIArgs{}
}

func (p *VoiceServiceDescribeAIArgs) InitDefault() {
}

var VoiceServiceDescribeAIArgs_Req_DEFAULT *DescribeReq

func (p *VoiceServiceDescribeAIArgs) GetReq() (v *DescribeReq) {
	if !p.IsSetReq() {
		return VoiceServiceDescribeAIArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VoiceServiceDescribeAIArgs) SetReq(val *DescribeReq) {
	p.Req = val
}

func (p *VoiceServiceDescribeAIArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VoiceServiceDescribeAIArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VoiceServiceDescribeAIArgs(%+v)", *p)
}

var fieldIDToName_VoiceServiceDescribeAIArgs = map[int16]string{
	1: "req",
}

type VoiceServiceDescribeAIResult struct {
	Success *string `thrift:"success,0,optional" frugal:"0,optional,string" json:"success,omitempty"`
}

func NewVoiceServiceDescribeAIResult() *VoiceServiceDescribeAIResult {
	return &VoiceServiceDescribeAIResult{}
}

func (p *VoiceServiceDescribeAIResult) InitDefault() {
}

var VoiceServiceDescribeAIResult_Success_DEFAULT string

func (p *VoiceServiceDescribeAIResult) GetSuccess() (v string) {
	if !p.IsSetSuccess() {
		return VoiceServiceDescribeAIResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *VoiceServiceDescribeAIResult) SetSuccess(x interface{}) {
	p.Success = x.(*string)
}

func (p *VoiceServiceDescribeAIResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VoiceServiceDescribeAIResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VoiceServiceDescribeAIResult(%+v)", *p)
}

var fieldIDToName_VoiceServiceDescribeAIResult = map[int16]string{
	0: "success",
}

type VoiceServiceGetRankingsArgs struct {
	Req *RankingsReq `thrift:"req,1" frugal:"1,default,RankingsReq" json:"req"`
}

func NewVoiceServiceGetRankingsArgs() *VoiceServiceGetRankingsArgs {
	return &VoiceServiceGetRankingsArgs{}
}

func (p *VoiceServiceGetRankingsArgs) InitDefault() {
}

var VoiceServiceGetRankingsArgs_Req_DEFAULT *RankingsReq

func (p *VoiceServiceGetRankingsArgs) GetReq() (v *RankingsReq) {
	if !p.IsSetReq() {
		return VoiceServiceGetRankingsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VoiceServiceGetRankingsArgs) SetReq(val *RankingsReq) {
	p.Req = val
}

func (p *VoiceServiceGetRankingsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VoiceServiceGetRankingsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VoiceServiceGetRankingsArgs(%+v)", *p)
}

var fieldIDToName_VoiceServiceGetRankingsArgs = map[int16]string{
	1: "req",
}

type VoiceServiceGetRankingsResult struct {
	Success *PaginatedVoices `thrift:"success,0,optional" frugal:"0,optional,PaginatedVoices" json:"success,omitempty"`
}

func NewVoiceServiceGetRankingsResult() *VoiceServiceGetRankingsResult {
	return &VoiceServiceGetRankingsResult{}
}

func (p *VoiceServiceGetRankingsResult) InitDefault() {
}

var VoiceServiceGetRankingsResult_Success_DEFAULT *PaginatedVoices

func (p *VoiceServiceGetRankingsResult) GetSuccess() (v *PaginatedVoices) {
	if !p.IsSetSuccess() {
		return VoiceServiceGetRankingsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VoiceServiceGetRankingsResult) SetSuccess(x interface{}) {
	p.Success = x.(*PaginatedVoices)
}

func (p *VoiceServiceGetRankingsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VoiceServiceGetRankingsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VoiceServiceGetRankingsResult(%+v)", *p)
}

var fieldIDToName_VoiceServiceGetRankingsResult = map[int16]string{
	0: "success",
}

type VoiceServiceIncrementStatArgs struct {
	Req *IncrementStatReq `thrift:"req,1" frugal:"1,default,IncrementStatReq" json:"req"`
}

func NewVoiceServiceIncrementStatArgs() *VoiceServiceIncrementStatArgs {
	return &VoiceServiceIncrementStatArgs{}
}

func (p *VoiceServiceIncrementStatArgs) InitDefault() {
}

var VoiceServiceIncrementStatArgs_Req_DEFAULT *IncrementStatReq

func (p *VoiceServiceIncrementStatArgs) GetReq() (v *IncrementStatReq) {
	if !p.IsSetReq() {
		return VoiceServiceIncrementStatArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VoiceServiceIncrementStatArgs) SetReq(val *IncrementStatReq) {
	p.Req = val
}

func (p *VoiceServiceIncrementStatArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VoiceServiceIncrementStatArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VoiceServiceIncrementStatArgs(%+v)", *p)
}

var fieldIDToName_VoiceServiceIncrementStatArgs = map[int16]string{
	1: "req",
}

type VoiceServiceIncrementStatResult struct {
	Success *Voice `thrift:"success,0,optional" frugal:"0,optional,Voice" json:"success,omitempty"`
}

func NewVoiceServiceIncrementStatResult() *VoiceServiceIncrementStatResult {
	return &VoiceServiceIncrementStatResult{}
}

func (p *VoiceServiceIncrementStatResult) InitDefault() {
}

var VoiceServiceIncrementStatResult_Success_DEFAULT *Voice

func (p *VoiceServiceIncrementStatResult) GetSuccess() (v *Voice) {
	if !p.IsSetSuccess() {
		return VoiceServiceIncrementStatResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VoiceServiceIncrementStatResult) SetSuccess(x interface{}) {
	p.Success = x.(*Voice)
}

func (p *VoiceServiceIncrementStatResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VoiceServiceIncrementStatResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VoiceServiceIncrementStatResult(%+v)", *p)
}

var fieldIDToName_VoiceServiceIncrementStatResult = map[int16]string{
	0: "success",
}

type VoiceServiceAdminListArgs struct {
	Req *AdminListVoicesReq `thrift:"req,1" frugal:"1,default,AdminListVoicesReq" json:"req"`
}

func NewVoiceServiceAdminListArgs() *VoiceServiceAdminListArgs {
	return &VoiceServiceAdminListArgs{}
}

func (p *VoiceServiceAdminListArgs) InitDefault() {
}

var VoiceServiceAdminListArgs_Req_DEFAULT *AdminListVoicesReq

func (p *VoiceServiceAdminListArgs) GetReq() (v *AdminListVoicesReq) {
	if !p.IsSetReq() {
		return VoiceServiceAdminListArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VoiceServiceAdminListArgs) SetReq(val *AdminListVoicesReq) {
	p.Req = val
}

func (p *VoiceServiceAdminListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VoiceServiceAdminListArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VoiceServiceAdminListArgs(%+v)", *p)
}

var fieldIDToName_VoiceServiceAdminListArgs = map[int16]string{
	1: "req",
}

type VoiceServiceAdminListResult struct {
	Success *PaginatedVoices `thrift:"success,0,optional" frugal:"0,optional,PaginatedVoices" json:"success,omitempty"`
}

func NewVoiceServiceAdminListResult() *VoiceServiceAdminListResult {
	return &VoiceServiceAdminListResult{}
}

func (p *VoiceServiceAdminListResult) InitDefault() {
}

var VoiceServiceAdminListResult_Success_DEFAULT *PaginatedVoices

func (p *VoiceServiceAdminListResult) GetSuccess() (v *PaginatedVoices) {
	if !p.IsSetSuccess() {
		return VoiceServiceAdminListResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VoiceServiceAdminListResult) SetSuccess(x interface{}) {
	p.Success = x.(*PaginatedVoices)
}

func (p *VoiceServiceAdminListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VoiceServiceAdminListResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VoiceServiceAdminListResult(%+v)", *p)
}

var fieldIDToName_VoiceServiceAdminListResult = map[int16]string{
	0: "success",
}

type VoiceServiceAdminUpdateArgs struct {
	Req *AdminUpdateVoiceReq `thrift:"req,1" frugal:"1,default,AdminUpdateVoiceReq" json:"req"`
}

func NewVoiceServiceAdminUpdateArgs() *VoiceServiceAdminUpdateArgs {
	return &VoiceServiceAdminUpdateArgs{}
}

func (p *VoiceServiceAdminUpdateArgs) InitDefault() {
}

var VoiceServiceAdminUpdateArgs_Req_DEFAULT *AdminUpdateVoiceReq

func (p *VoiceServiceAdminUpdateArgs) GetReq() (v *AdminUpdateVoiceReq) {
	if !p.IsSetReq() {
		return VoiceServiceAdminUpdateArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VoiceServiceAdminUpdateArgs) SetReq(val *AdminUpdateVoiceReq) {
	p.Req = val
}

func (p *VoiceServiceAdminUpdateArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VoiceServiceAdminUpdateArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VoiceServiceAdminUpdateArgs(%+v)", *p)
}

var fieldIDToName_VoiceServiceAdminUpdateArgs = map[int16]string{
	1: "req",
}

type VoiceServiceAdminUpdateResult struct {
	Success *Voice `thrift:"success,0,optional" frugal:"0,optional,Voice" json:"success,omitempty"`
}

func NewVoiceServiceAdminUpdateResult() *VoiceServiceAdminUpdateResult {
	return &VoiceServiceAdminUpdateResult{}
}

func (p *VoiceServiceAdminUpdateResult) InitDefault() {
}

var VoiceServiceAdminUpdateResult_Success_DEFAULT *Voice

func (p *VoiceServiceAdminUpdateResult) GetSuccess() (v *Voice) {
	if !p.IsSetSuccess() {
		return VoiceServiceAdminUpdateResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VoiceServiceAdminUpdateResult) SetSuccess(x interface{}) {
	p.Success = x.(*Voice)
}

func (p *VoiceServiceAdminUpdateResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VoiceServiceAdminUpdateResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VoiceServiceAdminUpdateResult(%+v)", *p)
}

var fieldIDToName_VoiceServiceAdminUpdateResult = map[int16]string{
	0: "success",
}

type VoiceServiceAdminDeleteArgs struct {
	Id int64 `thrift:"id,1" frugal:"1,default,i64" json:"id"`
}

func NewVoiceServiceAdminDeleteArgs() *VoiceServiceAdminDeleteArgs {
	return &VoiceServiceAdminDeleteArgs{}
}

func (p *VoiceServiceAdminDeleteArgs) InitDefault() {
}

func (p *VoiceServiceAdminDeleteArgs) GetId() (v int64) {
	return p.Id
}
func (p *VoiceServiceAdminDeleteArgs) SetId(val int64) {
	p.Id = val
}

func (p *VoiceServiceAdminDeleteArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VoiceServiceAdminDeleteArgs(%+v)", *p)
}

var fieldIDToName_VoiceServiceAdminDeleteArgs = map[int16]string{
	1: "id",
}

type VoiceServiceAdminDeleteResult struct {
	Success *bool `thrift:"success,0,optional" frugal:"0,optional,bool" json:"success,omitempty"`
}

func NewVoiceServiceAdminDeleteResult() *VoiceServiceAdminDeleteResult {
	return &VoiceServiceAdminDeleteResult{}
}

func (p *VoiceServiceAdminDeleteResult) InitDefault() {
}

var VoiceServiceAdminDeleteResult_Success_DEFAULT bool

func (p *VoiceServiceAdminDeleteResult) GetSuccess() (v bool) {
	if !p.IsSetSuccess() {
		return VoiceServiceAdminDeleteResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *VoiceServiceAdminDeleteResult) SetSuccess(x interface{}) {
	p.Success = x.(*bool)
}

func (p *VoiceServiceAdminDeleteResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VoiceServiceAdminDeleteResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VoiceServiceAdminDeleteResult(%+v)", *p)
}

var fieldIDToName_VoiceServiceAdminDeleteResult = map[int16]string{
	0: "success",
}

type VoiceServiceCountAllArgs struct {
}

func NewVoiceServiceCountAllArgs() *VoiceServiceCountAllArgs {
	return &VoiceServiceCountAllArgs{}
}

func (p *VoiceServiceCountAllArgs) InitDefault() {
}

func (p *VoiceServiceCountAllArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VoiceServiceCountAllArgs(%+v)", *p)
}

var fieldIDToName_VoiceServiceCountAllArgs = map[int16]string{}

type VoiceServiceCountAllResult struct {
	Success *int64 `thrift:"success,0,optional" frugal:"0,optional,i64" json:"success,omitempty"`
}

func NewVoiceServiceCountAllResult() *VoiceServiceCountAllResult {
	return &VoiceServiceCountAllResult{}
}

func (p *VoiceServiceCountAllResult) InitDefault() {
}

var VoiceServiceCountAllResult_Success_DEFAULT int64

func (p *VoiceServiceCountAllResult) GetSuccess() (v int64) {
	if !p.IsSetSuccess() {
		return VoiceServiceCountAllResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *VoiceServiceCountAllResult) SetSuccess(x interface{}) {
	p.Success = x.(*int64)
}

func (p *VoiceServiceCountAllResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VoiceServiceCountAllResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VoiceServiceCountAllResult(%+v)", *p)
}

var fieldIDToName_VoiceServiceCountAllResult = map[int16]string{
	0: "success",
}

type VoiceServiceCountByVisibilityArgs struct {
	Visibility string `thrift:"visibility,1" frugal:"1,default,string" json:"visibility"`
}

func NewVoiceServiceCountByVisibilityArgs() *VoiceServiceCountByVisibilityArgs {
	return &VoiceServiceCountByVisibilityArgs{}
}

func (p *VoiceServiceCountByVisibilityArgs) InitDefault() {
}

func (p *VoiceServiceCountByVisibilityArgs) GetVisibility() (v string) {
	return p.Visibility
}
func (p *VoiceServiceCountByVisibilityArgs) SetVisibility(val string) {
	p.Visibility = val
}

func (p *VoiceServiceCountByVisibilityArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VoiceServiceCountByVisibilityArgs(%+v)", *p)
}

var fieldIDToName_VoiceServiceCountByVisibilityArgs = map[int16]string{
	1: "visibility",
}

type VoiceServiceCountByVisibilityResult struct {
	Success *int64 `thrift:"success,0,optional" frugal:"0,optional,i64" json:"success,omitempty"`
}

func NewVoiceServiceCountByVisibilityResult() *VoiceServiceCountByVisibilityResult {
	return &VoiceServiceCountByVisibilityResult{}
}

func (p *VoiceServiceCountByVisibilityResult) InitDefault() {
}

var VoiceServiceCountByVisibilityResult_Success_DEFAULT int64

func (p *VoiceServiceCountByVisibilityResult) GetSuccess() (v int64) {
	if !p.IsSetSuccess() {
		return VoiceServiceCountByVisibilityResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *VoiceServiceCountByVisibilityResult) SetSuccess(x interface{}) {
	p.Success = x.(*int64)
}

func (p *VoiceServiceCountByVisibilityResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VoiceServiceCountByVisibilityResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VoiceServiceCountByVisibilityResult(%+v)", *p)
}

var fieldIDToName_VoiceServiceCountByVisibilityResult = map[int16]string{
	0: "success",
}

type VoiceServiceValidateForUserArgs struct {
	Req *ValidateVoiceReq `thrift:"req,1" frugal:"1,default,ValidateVoiceReq" json:"req"`
}

func NewVoiceServiceValidateForUserArgs() *VoiceServiceValidateForUserArgs {
	return &VoiceServiceValidateForUserArgs{}
}

func (p *VoiceServiceValidateForUserArgs) InitDefault() {
}

var VoiceServiceValidateForUserArgs_Req_DEFAULT *ValidateVoiceReq

func (p *VoiceServiceValidateForUserArgs) GetReq() (v *ValidateVoiceReq) {
	if !p.IsSetReq() {
		return VoiceServiceValidateForUserArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VoiceServiceValidateForUserArgs) SetReq(val *ValidateVoiceReq) {
	p.Req = val
}

func (p *VoiceServiceValidateForUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VoiceServiceValidateForUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VoiceServiceValidateForUserArgs(%+v)", *p)
}

var fieldIDToName_VoiceServiceValidateForUserArgs = map[int16]string{
	1: "req",
}

type VoiceServiceValidateForUserResult struct {
	Success *Voice `thrift:"success,0,optional" frugal:"0,optional,Voice" json:"success,omitempty"`
}

func NewVoiceServiceValidateForUserResult() *VoiceServiceValidateForUserResult {
	return &VoiceServiceValidateForUserResult{}
}

func (p *VoiceServiceValidateForUserResult) InitDefault() {
}

var VoiceServiceValidateForUserResult_Success_DEFAULT *Voice

func (p *VoiceServiceValidateForUserResult) GetSuccess() (v *Voice) {
	if !p.IsSetSuccess() {
		return VoiceServiceValidateForUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VoiceServiceValidateForUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*Voice)
}

func (p *VoiceServiceValidateForUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VoiceServiceValidateForUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VoiceServiceValidateForUserResult(%+v)", *p)
}

var fieldIDToName_VoiceServiceValidateForUserResult = map[int16]string{
	0: "success",
}
